- cmd/osbuild-installer/main.go
When running in OpenShift, installer needs to listen on a different
address (and possibly different port, too). Allow a user to specify a
custom listen address via environment variable.
> 👂 Set a custom listen address if provided

- distribution/Dockerfile-ubi
Use the go-toolset ubi8 container to speed up the container build
process since it comes with golang right out of the box.
> 🚄 Speed up container build

- templates/image-builder.yml
OpenShift really does not like having the port number as a raw integer.
Wrap the port number in quotes to please OpenShift.
> openshift: Wrap port number in quotes

- build_deploy.sh
- pr_check.sh
AppSRE expects two scripts to be present in our repository:
* `pr_check.sh` for checking pull requests
* `build_deploy.sh` for building containers and pushing to quay.io
> 📜 Add AppSRE scripts

- templates/image-builder.yml
apps/v1 + Deployment is the old style.
v1 + DeploymentConfig is the new style.
> 🗞 openshift: Use modern v1 API for deployments

- templates/image-builder.yml
Using github-mirror[0] as a guide:
* Use double curly braces for integer values (will be left unquoted)
* Change `DeploymentConfig` to `Deployment`
* Change apiVersion for `Deployment` to `apps/v1`
[0] https://github.com/app-sre/github-mirror/blob/master/openshift/github-mirror.yaml
> 🔨 openshift: Fix deployment template

- templates/image-builder.yml
Make it easier to keep track of port mappings later.
> openshift: add name for service port mapping

- templates/image-builder.yml
Add liveness/readiness probes to the image-builder deployment so
OpenShift can detect issues and re-deploy the application without user
intervention.
Also add a name to the port used in the deployment.
> 🩺 openshift: Add live/ready probes

- templates/image-builder.yml
Apparently OpenShift does not like port names longer than 15 characters. 🤷🏻‍♂️
Fixes #34
> ✂ openshift: shorten deployment port name

- templates/image-builder.yml
image-builder listens only on localhost by default, so we need to
specify the listen address inside the container so the port is
accessible within the cluster.
> 👂 openshift: listen on all addresses

- templates/image-builder.yml
Now that we have a identity header requirement, pass this header when
doing health checks.
> openshift: Add identity header for health check

- Makefile
- cmd/image-builder-tests/main_test.go
- internal/server/api.go
- internal/server/api.yaml
- internal/server/server.go
---
This contains mostly little adjustments to be compliant with clouddot guidelines.
They also prefer using the content-Type `application/vnd.api+json` however echo doesn't really support this, and it would require overwriting headers, or encoding the response into json ourselves etc... so I'd just leave it unless it turns out to be a real problem.
> Error handling

- templates/image-builder.yml
Let's work out bugs that arise from running more than one replica of image-builder in OpenShift by increasing the replica count to 2.
> openshift: run 2 replicas

- distribution/Dockerfile-ubi
- distribution/openshift-startup.sh
- templates/image-builder.yml
Add the AWS Cloudwatch configuration and credentials to the deployment for logging. Also, use a startup script for image-builder that prints some diagnostic information about its database connection and where to find logs in AWS.
> Add cloudwatch configuration and startup script

- templates/image-builder.yml
All of the cloudwatch variables are now in secrets.
> 🤦 openshift: Remove old cloudwatch vars

- templates/image-builder.yml
The image-builder code is looking for `CW_LOG_GROUP` and not `CW_LOG_GROUP_NAME`.
> 🔧 openshift: fix cloudwatch log group var

- cmd/image-builder/config.go
- cmd/image-builder/config_test.go
- cmd/image-builder/main.go
Instead of defining them in tags, define them when creating the object.
> image-builder: Specify config default values when creating it

- .github/workflows/tests.yml
was copied from another repository where branch names are different
> tests: Rename branch in GitHub workflow config file

- Makefile
- cmd/image-builder-tests/main_test.go
- cmd/image-builder/config.go
- cmd/image-builder/config_test.go
- cmd/image-builder/main.go
- distributions/fedora-32.json
- distributions/rhel-8.json
- internal/cloudapi/cloudapi_client.go
- internal/cloudapi/cloudapi_client.yml
- internal/server/api.go
- internal/server/api.yaml
- internal/server/server.go
- schutzbot/Jenkinsfile
- schutzbot/provision-composer.sh
Secrets should be accessible by image-builder, and added to the request
for composer. The user should only have to give their aws account id to
share the image with.
Region for now should be filled by image-builder as well.
> server: Only require Region and ShareWithAccounts for aws upload

- .github/workflows/container.yml
Also it now actually fails when the source wasn't prepared.
> workflows: The source prepare check moved to the tests workflow

- templates/image-builder.yml
We need 946a0b4 so we can run the composer-api on a non-privileged port.
> templates: Bump osbuild-composer version

- templates/image-builder.yml
Splitting the image-builder and osbuild-composer configurations allows
us to scale each one independently and deploy each one independently.
> ✂ Split image-builder/osbuild-composer deployment configs

- templates/image-builder.yml
Add a passthrough route to OpenShift to allow workers to reach
osbuild-composer.
> 🚪 Add route for osbuild-composer

- templates/image-builder.yml
Some of the secrets from the image-builder deployment should have been
moved to the osbuild-composer deployment.
> 🤫 Move secrets to osbuild-composer deployment

- templates/image-builder.yml
Use the proper port name (`osbuild-composer-cloudapi`) for the service
URL and switch the port number to 443 (the default).
> Fix composer ports/service linkage

- templates/image-builder.yml
In #89 the composer client config within image-builder got moved to the
composer container in a separate deployment. However image-builder needs
this information rather than composer.
---
I know there's a lot of doubts rn if we'll even run composer within the cluster but hey, this should at least remove the 500 error :)
> templates: Move composer client configuration in image-builder

- templates/image-builder.yml
Composer moved to aws.composer.osbuild.org, and it's not clear if we'll
be able to deploy composer inside of the same cluster as image-builder
in future.
> templates: Remove composer from deployment

- cmd/image-builder-tests/main_test.go
- cmd/image-builder/config.go
- cmd/image-builder/main.go
- internal/server/server.go
- internal/server/server_test.go
- internal/tutils/tutils.go
- schutzbot/run_tests.sh
- templates/image-builder.yml
For now when the environment is empty the filter won't apply.
> server: Allow filtering on org_id from the identity header

- templates/image-builder.yml
We're not using these anyway, and they currently break production.
> templates: Disable mapping db secrets to env for now

- cmd/image-builder/main.go
- internal/server/server.go
- internal/server/server_test.go
The previous check to see if the id was contained in a string didn't
take into account that organization ids might differ in length. And thus
if any id was a substring of the allowed ids, it could get acccess.
> server: Fix edge case in organization id filter

- internal/server/api.go
- internal/server/api.yaml
The upload_status property moved to image_status.
Remove double definition of compose status contents.
---
I got this wrong in #127 yet it somehow didn't produce any sideeffects.
> server: Clean up status yml

- distributions/centos-8.json
I made a mistake in my original PR: I used a mirrorlist for a "classic"
Centos 8. I could have fixed it by s/8/8-stream but I decided to drop the
mirrorlist. The reason is that in AWS it returns the
d36uatko69830t.cloudfront.net mirror. This mirror is amazingly fast but from
my experience, it can be often desynchronized. The plain dnf can handle it
but osbuild doesn't really like desynchronized repos. Therefore I switched
to mirror.centos.org which should be much more stable in this regard.
btw from /etc/yum.repos.d/ on centos stream 8:
```
[baseos]
name=CentOS Stream $releasever - BaseOS
mirrorlist=http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=BaseOS&infra=$infra
#baseurl=http://mirror.centos.org/$contentdir/$stream/BaseOS/$basearch/os/
```
This means that using …
> distributions: fix the centos stream 8 repo

- templates/image-builder.yml
Use separate endpoints for the liveness and the readiness probes as now
image-builder has both /status and /ready.
Depends on: #130
> template: Use the new readiness probe endpoint

- cmd/image-builder-tests/main_test.go
- cmd/image-builder/config.go
- cmd/image-builder/main.go
- internal/cloudapi/cloudapi_types.go
- internal/cloudapi/cloudapi_types.yml
- internal/server/api.go
- internal/server/api.yaml
- internal/server/server.go
- internal/server/server_test.go
- schutzbot/provision-composer.sh
- templates/image-builder.yml
This commit adds support for the Azure target throughout all image-builder layers. Also, osbuild-composer's version in provision-composer was bumped to support the azure target.
> Add support for Azure

- internal/server/distribution.go
- internal/server/server_test.go
Return 400 Bad Request instead of 500 when the distribution is
not supported.
> server: return bad request when distribution unsupported

- internal/server/distribution.go
Previously contained gosec overrides for G304 and G307, amend code so that the
overrides can be safely removed without triggering gosec violations. Clean
filepaths before calling os.Open and remove instances of deferring f.Close
so that errors can be caught before return.
> server: un-disable gosec

- internal/cloudapi/cloudapi_types.go
- internal/cloudapi/cloudapi_types.yml
- internal/server/api.go
- internal/server/api.yaml
- internal/server/server.go
- schutzbot/Jenkinsfile
- schutzbot/deploy.sh
- test/README.md
- test/cases/api.sh
Update composer cloudapi types related to upload options.
Expose upload options, returned from composer, in the image-builder API.
These contain all the necessary information to identify the uploaded
image in the specific cloud provider environment.
Integration testing:
- Test compose request for all supported cloud providers (AWS, Azure,
GCP).
- Verify the returned upload options for each cloud provider. Use it
to verify the resulting image from the compose by creating a VM in the
respective cloud provider environment and connecting to it via SSH
(except for Azure, where it is not possible because of a bug).
- Modify the way test cases are executed based on PR#79. Specifically
that the compose is tested only once for `BaseUrl`.
- Clean up WORKDIR at the end of the test run.
- Update …
> Expose upload options via API and extend integration testing for all cloud providers

- schutzbot/Jenkinsfile
- schutzbot/deploy.sh
Modify `schutzbot/deploy.sh` to try to use the actual commits of
osbuild and osbuild-composer deployed in staging / production for CI
runs on main (staging) and stable (production) branches. The same
applies for PRs to main and stable branches. For any other situation, use
the default values defined in `deploy.sh`.
> CI: use osbuild and composer commits deployed in staging / production

- internal/server/server.go
- internal/server/server_test.go
.meta.Count should contain the total amount of records, not the amount
of returned records.
> server: Fix pagination of the packages endpoint

- templates/image-builder.yml
The port on which `/metrics` is served does not differ from the rest.
> templates: Use default service port

- .github/workflows/container.yml
GitHub gets confused by the `:`, even though it is quoted. Putting it on a separate line fixes it.
Linter says: "incomplete explicit mapping pair; a key nodes is missed; or followed by a non-tabulated empty line"
> workflow/container: fix syntax error

- internal/server/prometheus.go
- internal/server/server.go
- internal/server/server_test.go
Regular counters get initiated to 0, and with countervectors we're
collecting a bunch of data we don't want. Let's target the metrics we
want to collect very specifically, and make our job easier when writing
rules around those metrics.
> prometheus: Use regular counters instead of countervectors

- internal/cloudapi/client.go
- internal/cloudapi/cloudapi_types.go
- internal/cloudapi/cloudapi_types.yml
- internal/server/api.go
- internal/server/api.yaml
- internal/server/server.go
- schutzbot/deploy.sh
- test/cases/api.sh
Added metadata API endpoint (composes/id/metadata) that returns the information from the equivalent endpoint in osbuild-composer:
- packages: full list of package NEVRAs included in the image.
- ostree_commit: the ID/hash of the ostree commit that was created (for edge types only)
Depends on osbuild/osbuild-composer#1490
> API: new endpoint '/composes/{id}/metadata'

- .gitlab-ci.yml
Removed in osbuild-composer repo and doesn't seem to actually be used
here.
> ci: Remove EXTRA_REPO_PATH_SEGMENT variable

- distributions/rhel-84.json
This is an alternative to rhel-edge-commit, which has the same payload, but in 8.4 it
supports embedding ssh keys, which rhel-edge-commit does not. The Edge API would
like to use this, so add the image type to the allow-list.
cc @aaronh88
> image-types/rhel84: add rhel-edge-container

- image-builder.spec
- test/cases/edge.sh
This pr contains:
Test edge installer iso image, includes:
- call rest api to generate iso image, 
- use mkksiso to put ks file into iso, 
- install edge with iso file
- run ansible scirpt to check edge vm.
> add test case for edge iso image

- .gitlab-ci.yml
- schutzbot/build.sh
- schutzbot/deploy.sh
- test/cases/api.sh
**ready for review now**
Move build.sh out of test stages. 
Push image-builder image into quay.io/osbuild/image-builder-test repo with CI_PIPELINE_ID as tag.
Archive image-builder packages as artifacts and set expire time as 3 days.
> [QE] Move build.sh to a new stage

- templates/image-builder.yml
The example ConfigMap wasn't used.
> templates: Remove unused openshift objects

- test/cases/edge.sh
Add test case to verify the metadata of edge images
- verify package in commit tar image
- redirect output to /dev/null because of log size limit in ci job console
> add test case to verify metadata of edge images

- image-builder.spec
- test/cases/edge.sh
- tools/gen-ssh.sh
Use newly generated ssh keys instead of hard codded ones
> tests: remove hard coded ssh keys

- internal/db/db.go
- internal/tutils/tutils.go
- internal/v1/server.go
- internal/v1/server_test.go
- schutzbot/deploy.sh
- test/cases/api.sh
Before accessing a compose status, the value of the identity header is
checked against the database to ensure that the user getting the
information is the same that made the request.
> Compose: No cross user compose access

- .github/dependabot.yml
- .github/workflows/trigger-gitlab.yml
dependabot is an independent security scanning tool which mostly focuses on evaluating the dependency chain. Having the dependabot.yml file on the main branch would enable the bot to test the dependencies and create a pull request for each one, on a specified schedule.
When we finish dependabot configuration tweaking in osbuild-composer repository, we can merge this PR.
> [CI] enable dependabot

- internal/db/migrate.go
This is an indication that a previous migration failed and manual
interaction is required.
> db: If db is dirty, do not continue with migration

- internal/common/prometheus.go
Compose requests can take anywhere from 3 to 12 seconds, and the default
buckets put everything above 10 in the infinite bucket. By introducing
more buckets compose requests should be captured better.
---
Note that the first 5 buckets are considered acceptable for non-compose requests. And the first 17 acceptable for compose requests. Anything above 12 for compose requests is considered (really) slow.
> prometheus: Custom buckets for http request duration histogram

- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
Unfortunately the image-builder-crc dashboard is no longer visible at all. The app-sre team suggested moving this dashboard over to the newly created Image-Builder folder.
> templates: change grafana folder

- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
The current dashboard is still not showing in stage or production and it's possibly
due to a conflict with the name and id. App-sre has suggested changing this to
resolve the issue.
> templates: change dashboard name & id

- internal/v1/api.go
- internal/v1/api.yaml
Add rhel-85 to /package endpoint
I'm getting this error when trying to search for rhel-85 package:
`{
"detail": "parameter \"distribution\" in query has an error: value is not one of the allowed values\nSchema:\n  {\n    \"enum\": [\n      \"rhel-84\",\n      \"centos-8\"\n    ],\n    \"type\": \"string\"\n  }\n\nValue:\n  \"rhel-85\"\n",
"title": "400"
}`
> add rhel-85 to package endpoint

- cmd/image-builder/main.go
- internal/composer/client.go
- internal/config/config.go
- internal/v1/server_test.go
@Gundersanne @ondrejbudai I've had to re-add some tls config when creating the composer`client. I've tried to make the changes as noninvasive as possible. The reason for this is that in the dev stack the backend is unable to communicate with the composer instance because of self-signed certs (https://github.com/osbuild/image-builder/issues/291)
I'm not sure if we want to include this "fix", so I've marked it as draft for now and happy to hear your thoughts.
> composer: add tls config

- templates/image-builder.yml
We don't actually use any file-based secrets anymore so let's just drop it.
> templates: drop the secrets volume

- internal/db/db.go
Add call to result.Err() after rows are closed by result.Next()
to check for invalid SQL not caught by earlier error handling.
> db: check for err after rows closed

- internal/composer/openapi.v2.gen.go
- internal/v1/server.go
- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
This way the generated url on app-sre's grafana instances will always be
`...d/image-builder-crc`.
---
I plan to update all references to the dashboard after this, and then we'll hopefully never have to make sure the urls are up to date ever again :)
> templates/dashboards: Set uid to a fixed string

- distributions/rhel-84.json
- distributions/rhel-85.json
The spec was edited to support these image types, but they're just aliases of older ones as we haven't dropped the upload_request in image-builder. But the distros should be updated to reflect these, otherwise it'll refuse to build the types we advertise as available in the spec.
> distributions: Align available image types with spec

- internal/composer/openapi.v2.gen.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/server.go
Composer returns a structured error in the case of a failed build. This
PR adds support to image builder for these errors:
> Structured errors

- .gitlab-ci.yml
with #326, every testing resources will be removed by scheduled cloud
cleaner running on osbuild-composer. We can enable auto-cancel redundant
pipelines. To do so, every job must be interruptible
> ci: make every job interruptible

- test/cases/api.sh
SSIA
```bash
thozza@fedora ~/devel/image-builder (main=)
$ grep -r API_TEST_SUBSCRIPTION_ACTIVATION_KEY
test/cases/api.sh:      "activation-key": "${API_TEST_SUBSCRIPTION_ACTIVATION_KEY:-}",
test/cases/api.sh:      "activation-key": "${API_TEST_SUBSCRIPTION_ACTIVATION_KEY:-}",
test/cases/api.sh:      "activation-key": "${API_TEST_SUBSCRIPTION_ACTIVATION_KEY:-}",
```
> CI: rotate the used RHSM activation key

- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
The dashboard was still showing two separate graphs for latency requests - one for long-running
compose requests and a separate one for normal requests. This commit merges the two graphs and
adds descriptions to each of the panels, giving information on the current targets.
The temp dashboard can be found [here](https://grafana.stage.devshift.net/d/image-builder-crc-test/image-builder-crc-test?orgId=1&var-datasource=crcs02ue1-prometheus&var-interval=28d&var-stability_slo=0.95&var-latency_slo=0.95&from=now-28d&to=now)
Screenshot:
> templates/dashboard: merge request graphs

- distribution/Dockerfile-ubi
I don't see a reason why not to be honest. As Red Hatters, we should promote
using our latest and greatest technologies in tech stacks so choosing UBI9
as the base for our deployments seems natural. Also, it's just golang,
I'm pretty sure that this will work just fine.
> Dockerfile: use ubi9 as the base images

- .github/workflows/tests.yml
- templates/.kube-linter-config.yml
- templates/iqe-trigger.yml
Example runs: https://github.com/Gundersanne/image-builder/actions/workflows/tests.yml.
The 'break template' commits are commits where the check was made to fail on purpose.
> Add kube-linter check

- templates/iqe-trigger.yml
Apparently the name can contain only lowercase alphanumeric characters
so removing the uppercase ones.
> template: fix iqe-trigger name

- internal/composer/openapi.v2.gen.go
This commit updates the composer api spec, necessary due to
https://github.com/osbuild/osbuild-composer/pull/2666
> Composer: Update spec

- internal/composer/openapi.v2.gen.go
- internal/v1/server.go
The internal error wasn't set properly, resulting in the error handler
not logging it.
---
I want to replace this with the composer client being able to parse the error fully. But this will do for now.
> v1: Log errors coming from composer

- internal/v1/server.go
This changed in https://github.com/osbuild/osbuild-composer/pull/2748,
where the targeterror is appended to the details instead of being set as
the top-level job error.
> v1: Attempt to parse target error's details as new compose error

- internal/v1/server.go
26 is a generic dependency failure, similar to 5 and 9 which are for the
manifest's depsolve dependency and osbuild's manifest dependency
failures. Future dependency errors will use 26 unless there's an
indication to capture it separately.
> v1: Attempt to parse error details as compose error for 26

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/server.go
- internal/v1/server_test.go
Expose user account customization in image builder, and add tests that:
i. ensure that user customization is only permitted for installer image types
ii. image-builder compose requests are being translated correctly into the expected osbuild-composer compose requests (i.e. IB adds wheel group)
> v1: expose user customization

- test/cases/api.sh
For now, resources should be tagged with `gitlab-ci-test` in order to get cleaned up by cloud cleaner. This test was not tagging the and some resources were being left behind.
> test: tag azure resources in api.sh

- schutzbot/deploy.sh
- templates/image-builder.yml
Newer service accounts only work with RH SSO. Older accounts work with both Openshift and RH SSO. Let's just switch to using RH SSO in case the service accounts ever need to be reprovisioned.
> templates: Grab access tokens from RH SSO

- internal/composer/openapi.v2.gen.go
osbuild/osbuild-composer#2897 added the ability to mark an s3 artifact as public.
> composer: api spec update

- internal/composer/openapi.v2.gen.go
IoT was added here:
https://github.com/osbuild/osbuild-composer/commit/fc4450cfbf73b361f180276d6c154a21326a3edc
> composer: re-generate the API types

- cmd/image-builder/main.go
- internal/config/config_test.go
- internal/config/utils.go
The migration entrypoint didn't pick up the additional clowder configurations.
> config: move clowder configuration to config package

- internal/composer/openapi.v2.gen.go
- internal/v1/handler.go
The GCP bucket is no longer a required variable.
> internal/composer: spec update

- .github/workflows/tests.yml
- .gitignore
- Makefile
- cmd/image-builder-db-test/main_test.go
- cmd/image-builder-migrate-db-tern/image-builder-migrate-db-tern.go
- distribution/Dockerfile-ubi
- internal/config/config.go
- internal/db/migrations-tern/001_create_table_composes.sql
- internal/db/migrations-tern/002_create_table_clones.sql
- schutzbot/deploy.sh
- templates/image-builder-clowder.yml
- templates/image-builder.yml
Tern uses transactions for each migration, so a failed migration can just be resolved by pushing a new version. Migrations with `golang-migrate` might result in a broken database which needs to be manually resolved.
This doesn't remove golang-migrate yet, as it runs the db-tests against a database migrated with golang-migrate and tern, and against a database migrated with just tern.
Fixes #197
> db: Switch to jackc/tern for migrations

- internal/v1/middleware.go
Previously returned a 500, change to return a 400
when FindRoute fails.
Fixes #426
> middleware: return 400 on route error

- .github/workflows/codeql.yml
LGTM.com is being deprecated (see
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/). The codeql analysis engine is available on GH however.
> .github/codeql: add codeql static analysis

- internal/v1/handler.go
- internal/v1/server_test.go
internal/v1: correctly deal with offsets in GetPackages
If the offset was 0, which is the default, and if no packages were
found, it panicked due to an out of bounds index.
The reasoning by subtracting one was that even if you chose too large of
an offset, it would still give you back something. Simply cap the offset
in case it's larger than the amount of packages. The data returned will
be empty but that's ok.
Also cap the last offset at 0 if no results were found.
> internal/v1: correctly cap offset in GetPackages

- internal/v1/handler.go
- internal/v1/server_test.go
Return an ISO8601 compliant datetime to facilitate easier parsing and comparison in the frontend.
Addresses #457
> internal/v1: ISO8601 datetime

- internal/v1/handler.go
Return 400 error code for clone post request when the parent compose has either failed or is still
running.
Fixes #448
> internal/v1: 400 error for failed compose clones

- templates/image-builder.yml
FloorPlan for data extraction based on sample [1] and Compliance's FloorPlan [2].
The query already runs weekly and is defined in app-interface.  With this FloorPlan, we will configure the Floorist operator to store the data in an S3 bucket in the Parquet format.
[1] https://github.com/RedHatInsights/compliance-backend/blob/822e2d9823d88a2ac01b2184c22e3a77827d411c/clowdapp.yaml#L272-L298
[2] https://github.com/RedHatInsights/compliance-backend/blob/822e2d9823d88a2ac01b2184c22e3a77827d411c/clowdapp.yaml#L272-L298
> templates: add FloorPlan

- templates/image-builder.yml
Keep the image-builder-clowder template for now as a copy, so the
ephemeral environment doesn't break (bonfire doesn't support symlinks).
> templates: move to ClowdApp for main deployment

- .github/workflows/tests.yml
Add ignore rules for cleanup functions called by trap because shellcheck can't distinguish that. Inspired by commit from Alex in osbuild-composer.
> Fix new issues reported by ShellCheck 0.9.0

- templates/image-builder-clowder.yml
- templates/image-builder.yml
Clowder webServices creates a service on port 8000, but the gateway has image-builder routed to 8080. Readd the old service object for now.
> templates: add openshift service object again

- templates/image-builder-clowder.yml
- templates/image-builder.yml
The pods generated by ClowdApp only has the 'app' and 'pod' labels.
> templates: fix service pod selector

- templates/image-builder-clowder.yml
- templates/image-builder.yml
The app and pod labels are set by Clowder when deploying the ClowdApp. While these shouldn't change, let's minimize the chance of breakage in case they do, and mimic other service's selector by only leaving the pod selector.
> templates: make service selector less strict

- .github/workflows/tests.yml
- internal/common/quota.go
- internal/composer/client.go
- internal/distribution/distribution.go
- internal/tutils/tutils.go
- internal/v1/handler.go
- internal/v1/server_test.go
tools/prepare-source uses go 1.18 as well, and the ubi9 container has go 1.18.
> .github/workflows: use go 1.18

- go.mod
- go.sum
- internal/tutils/idheader_utils.go
- internal/tutils/tutils.go
- internal/v1/server_test.go
- vendor/github.com/redhatinsights/identity/identity.go
- vendor/modules.txt
The old version requires account_number to be set still.
---
> go.mod: update redhatinsights/identity

- internal/v1/server.go
The platform switched from having a valid org_id to filtering on specific SKUs to determine RHEL entitlements. But it doesn't seem to work properly, disable it until the platform entitlements are sorted.
> internal/v1: disable RHEL entitlement check

- cmd/image-builder-db-test/main_test.go
- internal/db/migrations-tern/003_drop_account_number_constraint.sql
The account number is no longer required for RHEL entitlement by the platform, so it's allowed to be empty.
> internal/db: drop account_number_constraint

- internal/v1/handler.go
- internal/v1/server_test.go
the endpoint /composes/{id}/clones returned null instead of empty array if there were no clones.
HMS-163
> internal/v1: return empty array instead of null

- internal/v1/handler.go
gosec now errors on unhandled error from io.Closer.Close(). Since there's not a much we can do in this case, let's at least starting logging this. This should silence gosec and give us some insight if this is ever happening.
> v1: log when closing a response body fails

- .github/workflows/spec-update.yml
The default token can't be used if we want github actions to run, see https://github.com/peter-evans/create-pull-request#action-inputs.
Set the author to schutzbot as well.
> .github/workflows/spec-update: set pull request token and author

- test/README.md
These paths included my own home directory, leftover from long ago.
Setting some composer secrets is also required now, even if it's just
bogus values.
> test/README.md: remove random paths

- internal/v1/handler.go
In this case the response from sources is empty anyway, so let's just leave it out.
> v1: fix nil pointer dereference in compose handler

- pr_check.sh
We now have tests that integrate with other hms apps so we need to deploy them in the ephemeral environment too.
> pr_check: add other hms apps to deployment

- templates/iqe-trigger-integration.yml
This PR adds a template for a tekton pipeline job which will trigger end-to-end IQE tests on stage, after the stage post-deploy tests from iqe-trigger.yml have run.
(Merging this PR will not have any effect until the pipeline is created in app-interface.)
> templates: Add template for stage post-deploy end-to-end HMS testing

- templates/iqe-trigger-integration.yml
This PR makes a couple fixes the e2e test template:
- Only run tests once, in case of failure
- Pull the latest testing image each time
- Run tests against stage-beta environment
> templates: Fix template for stage post-deploy end-to-end HMS testing

- test/cases/api.sh
This package is installed to make sure the system is registered, which is already verified in the previous statements.
> test/cases/api: remove unnecessary package installation

- distribution/Dockerfile-ubi
- tools/prepare-source.sh
The latest 1.19 toolset breaks with:
```
RUN go install ./...
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
> distribution/Dockerfile-ubi: pin go toolset to go 1.18.10

- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
The continuous colour mode doesn't take into account the thresholds. Meaning the peaks will always be red, even if they're within the SLO target.
> dashboards: fix latency graph colours

- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
The SLO section always shows the last 28 days, and the operational section is only interesting over a shorter period of time, so reflect that in the default time and internal settings.
> templates/dashboards: show the last 6 hours by default

- distribution/Dockerfile-ubi
When `go install` is called, go tries to get the git commit hash and embed it
into the built binary. Internally, go just calls the git executable.
The newer go-toolset seems to be based on RHEL 9.2 that ships a newer version
of git (2.39.1). This version contains the safe directory patch that
disallows git from operating on repositories owned by different users.
Thus, we need to chown the files when copying.
See
https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory
> Dockerfile-ubi: chown the copied files and unpin go 

- templates/iqe-trigger-integration.yml
This PR updates the post-deploy e2e test template:
- Update resource names to not be specific to the stage environment
- Create an identifier string to pass to the test container's IQE_IBUTSU_SOURCE env value. This is used when reporting test results.
> templates: update e2e template names, add IQE_IBUTSU_SOURCE env value

- .github/workflows/tests.yml
- go.mod
- internal/common/allow.go
- internal/common/quota.go
- tools/prepare-source.sh
UBI and the oldest support Fedora (37) now all have go 1.19, so we are cleared to switch.
gofmt now reformats comments in certain cases, so that explains the formatting changes in this commit.
See https://go.dev/doc/go1.19#go-doc
> update to go 1.19

- templates/iqe-trigger-integration.yml
This PR updates the e2e post-deploy test template:
- The selenium container needs a higher memory limit, but can request in smaller chunks.
- The CPU chunks for the iqe container can be smaller, and its memory limit reduced
> templates: Adjust memory request and limit in e2e test template

- templates/iqe-trigger-integration.yml
This PR updates the e2e post-deploy test template to set two new environment variables, `IQE_BROWSERLOG=1` and `IQE_NETLOG=1`, so that any UI test failures will automatically capture and send browser logs to our test reporting portal.
> templates: Add browser log params to e2e test template

- templates/iqe-trigger-integration.yml
We are seeing some OOM errors during browser log collection. I'm hoping that increasing the limit will resolve this.
> Increase memory limit for selenium test container

- internal/v1/handler.go
- internal/v1/server_test.go
I believe there's no reason not to expose the customization for all image types. We actually strive to achieve a functional parity between the hosted service and on-premise IB, so this feels like a low-hanging fruit.
https://issues.redhat.com/browse/HMS-2211
> handler: allow using the user customization everywhere

- internal/v1/handler.go
- internal/v1/server_test.go
The filesystem customization is valid also in the case when there's just one: a user might want to create/expand just one partition.
Let's fix the condition that wasn't allowing this, and add a test.
> HMS-2397: handler: fix the filesystem customization when just one is specified

- internal/v1/handler.go
These errors are due to missing information in the compose request.
> v1: classify composer's 24 and 29 errors as 400

- templates/iqe-trigger-integration.yml
I want to be able to distinguish between the pods running the service tests or the integration tests. The actual value of the parameter will be set in the corresponding saas files in app-interface.
> templates: add TEST_TYPE parameter to testing job name

- .gitlab-ci.yml
We decided on our previous team meeting call,
https://docs.google.com/document/d/1kKxYEaXMxa85SINBaic8rf5k9twE1cfl3fMvtspzQLE/edit to only keep the azure test for the integration test of image builder as it's the fastest of the 3 in order to speed things up in ci.
> ci: speed up integration tests

- tools/prepare-source.sh
I noticed messy imports, so I propose `goimports` as well as `gofumpt` (a bonus). We find both tools not being intrusive. The patch introduces new script in the ./tools directory and moves formatting from prepare-source.sh.
> Formatting

- internal/db/migrations-tern/008_index_composes_org_id.sql
I noticed most queries filter records by org_id, however, there is no index on the column. With the current strategy of not deleting records from composes table, this might be a problem in the future causing too many table scans. This fixes it.
Warning: We now have three PRs with a migration, make sure we rename the numbers accordingly. Cheers. @croissanne
> db: add composes org id index

- internal/db/db.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler.go
- internal/v1/handler_get_compose_status_test.go
- internal/v1/handler_test.go
Clones should include their parent ID, to easily match them.
This follows rest standards.
I've got no idea how to do this properly, but I just felt it would be really nice to have compose_id in the clone detail response :thinking:
> v1: include compose_id in clone response

- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
- internal/db/db_blueprints.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler.go
- internal/v1/handler_blueprints.go
- internal/v1/handler_get_compose_status_test.go
- internal/v1/handler_post_compose_test.go
- internal/v1/handler_test.go
This adds a new endpoint for composing a blueprint.
path:`/experimental/blueprint/{id}/compose`
Added a FK for reference a blueprint in compose table
Versioning association if needed will be added as a follow-up
The compose's name needs to be generated, for now I used just blueprint's name (unify the blueprint's name with a sequence number?)
> api: add compose blueprint endpoint

- internal/db/db.go
This one is important otherwise connections will leak.
> db: add missing result close call

- test/README.md
Hello, this is only a suggestion, but I got confused by the inconsistency, and this might potentially help.
Here is the reason for the change, I got confused by the other repository expecting a different approach: https://github.com/osbuild/osbuild-getting-started/pull/17
> chore: update README file

- .github/workflows/spec-update.yml
Since this workflow calls prepare-source, it should setup go before running.
> .github: setup go in spec-update workflow

- internal/tutils/idheader_utils.go
- internal/v1/handler_blueprints_test.go
Add handler test for testing the Compose Blueprint endpoint. It tests whether the endpoint contacts the composer correct amount of time and retrives ID for each compose.
Follow-up for https://github.com/osbuild/image-builder/pull/940
> test: Add handler test for Compose Blueprint

- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
- internal/db/db_blueprints.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
```
GET /experimental/blueprints
````
This PR adds a blueprint list endpoint, which returns an array of blueprints (only the latest version of each blueprint) sorted by its latest version creation date.
Each blueprint item contains its id, name, description, latest version, version date.  body is not included.
A basic pagination with `limit` and `offset`  parameters is implemented.
> api: add blueprint list endpoint

- Makefile
- README.md
Updated Makefile and README to be consistent with osbuild and osbuild-composer
> Readme update

- cmd/image-builder-db-test/main_test.go
- internal/db/db_blueprints.go
This optimizes query in case no search is performed. In that case empty string is passed into the db function and the argument is `%%`. The change will help PostgreSQL optimizer to drop the rest of the where clause in order to quickly return results without any tablescan.
Refs: HMS-3308
> db: optimize blueprint search

- internal/v1/handler_post_compose_test.go
- internal/v1/handler_test.go
- internal/v1/server_identity_test.go
Some test cases used go literals as a HTTP error code, other uses digital const values. This commit unifies test to use only go defines for HTTP error codes.
> Tests: Unify HTTP error codes used in test cases

- templates/image-builder.yml
Other services rely on the label for discovery, since there's now 2 namespaces on the same cluster with the same service (the RHEL and community ones) the two get mixed up randomly.
> templates/image-builder: parametrise Service object label

- templates/image-builder.yml
Dependency discovery happens based on the name of the clowdapp, which is assumed to be unique inside of a single cluster.
> templates/image-builder: parametrise clowdapp name

- templates/image-builder.yml
The clowdapp name needs to be unique, not the service label.
This reverts commit a22d5a2e00e3f3e6eb90de3dd181110091558984.
> Revert "templates/image-builder: parametrise Service object label"

- cmd/image-builder/main.go
This reverts commit 07167854b11a19dc9ce550545e4d70a33283c8a5.
glitchtip issues are showing, no need for InfoLevel messages anymore
> Revert "image-builder: log Info messages to sentry as well"

- templates/image-builder.yml
The ClientID is being tracked in our database (https://github.com/osbuild/image-builder/pull/897) but as it's not included in the floorplan it doesn't get exported.
> templates: Include clientid in FloorPlan (HMS-3244)

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints_test.go
Although there is a precedent in using both plural and singular forms (composes/compose), I believe it is worth to be consistent.
The API is still experimental, so this patch is fine.
> v1: rename to blueprints

- templates/image-builder.yml
> templates/image-builder: fix fedora auth template variable

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
If the user or group of a file or directory wasn't specified, it would dereference a nil pointer.
> v1: fix file and directory customizations

- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
- internal/db/db_blueprints.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
Add special value parameter -1 for fetching latest blueprint version. Adds extra query for fetching the version, to keep the SQL simple and easy to read.
Refs: HMS-3412
> v1/api: composes filtering by latest blueprint version

- cmd/image-builder/main.go
Logs are polluted with these nonsense log entries, this should remove it according to docs (untested).
> cmd: skip infra paths logging

- distributions/fedora-40/fedora-40.json
Fedora has no modular content since Fedora 39. The metalinks for F39 just point to the Everything repositories, and the metalinks for F40 just don't exist at all (so if anything expects these URLs to actually work, it'll break).
> Drop modular repos from Fedora 39 and 40 configurations

- pr_check.sh
We don't test content-sources integration in ephemeral.
> pr_check: remove content-sources from deployment

- internal/db/migrations-tern/010_drop_blueprints_account_number_check.sql
Account number will be dropped soon, we do not want to enforce it.
This is blocking stage testing currently, as there is no account number in stage.
> db: drop account number check from blueprints

- .gitignore
- cmd/image-builder-db-test/main_test.go
- cmd/image-builder/logging.go
- cmd/image-builder/main.go
- internal/db/db.go
- internal/db/db_blueprints.go
- internal/db/db_trace.go
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
Logging is completely context-less meaning there is no correlation id available in kibana. This is the first step towards having logs fully correlated.
First, a request id is extracted or generated in a new middleware which also stores it in a newly created standard context. This standard context is then passed into logrus logger that has the context associated. Finally, logrus has a new hook that extract the request id from the standard context and creating a text field.
On top of that, pgx driver is configured with a newly created tracer hook which logs SQL queries via debug level with context in mind. As long as the proper standard context is passed into
What it all means: if we pass context down the stack to pgx (and other functions or libraries in the future), we will get fully …
> main: make echo logger context aware

- cmd/image-builder/main.go
- internal/common/runtime.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler.go
I was not sure recently if my change was pushed to stage or not. Since the version endpoint returns just 1.0 that does not help at all, this patch adds sha commit and build datetime:
```
$HOME/bin/curl-local-ib GET /image-builder/v1/version
{
"build_commit": "898e84",
"build_time": "2024-02-28T07:25:03Z",
"version": "1.0"
}
```
It also prints the same in logs while starting the app.
> v1: return commit sha via version endpoint

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_compose_image.go
This is needed to workaround Akamai content filter which goes nuts the moment it sees `/usr/bin/`. All requests containing this in body are refused with 403.
https://issues.redhat.com/browse/HMS-3581
> v1/api: add base64-encoded file data

- internal/v1/handler.go
- internal/v1/handler_blueprints.go
- internal/v1/handler_compose_image.go
This is a followup for my logging improvement patch. This ensures the echo context is passed around. Generally speaking, instead of:
```
logrus.Info(...)
```
write:
```
ctx.Logger().Info(...)
```
That is all that needs to be done. In the next patch, I will update the db functions to accept context.
> v1: pass echo context through handlers

- pr_check.sh
This marker doesn't include the clone test. Also dropping provisioning from the deployment as we don't test the integration here.
> pr_check: use new marker

- internal/common/pointers.go
- internal/v1/handler_blueprints.go
Frontend might submit an empty search in `/blueprints` endpoint, which trigger a redundant search query in DB
> API: verify search param is not empty in /blueprints

- Makefile
- cmd/image-builder-db-test/main_test.go
- test/README.md
Improve error handling when tern command fails. It was a pain to debug this.
I also noticed I made an incorrect edit during my other change when I broke the build make target into multiple command, this fixes it:
https://github.com/osbuild/image-builder/commit/acbb3e6355698f6652a4e9ae8ce234dd8ea6a06e
> cmd/image-builder-db-test: improve tern error

- cmd/image-builder/logging.go
- cmd/image-builder/main.go
- internal/common/echo_logrus.go
- internal/v1/server.go
- internal/v1/server_identity.go
This pull request fixes an issue with the logging context in the Echo middleware. Previously, the context was not being passed correctly, resulting in incorrect log messages. This PR updates the code to ensure that the context is properly passed to the logger.
Example log output with this patch (see request id and insights id being propagated through the whole lifecycle of the request:
```
time="2024-03-27T09:47:35+01:00" level=warning msg="Sentry/Glitchtip was not initialized" func=main.main file="/Users/lzap/Work/image-builder/cmd/image-builder/main.go:57"
time="2024-03-27T09:47:35+01:00" level=info msg="🚀 Starting image-builder built 2024-03-26T18:07:06Z sha 916b5b server on localhost:8086 ...\n" func=main.main file="/Users/lzap/Work/image-builder/cmd/image-builder/main.go:176"
⇨ http …
```
> cmd: pass context into echo logger

- internal/v1/api.yaml
- internal/v1/handler_post_compose_test.go
In PR #1096 when the option was added, I wrote in the description that groups must be prefixed with @.  The correct character is actually %.
> internal/v1: fix the documented group prefix for sudo-nopasswd

- templates/iqe-trigger-integration.yml
New sel image is failing the test pipeline because it does not have a controlled shutdown command, making the pod stuck and resulting into timeout.
> templates/testing: IQE-2748 Revert Update sel testing image backend

- internal/config/utils.go
The specific deployment that ib needs to target is called `service`.
---
see https://github.com/content-services/content-sources-backend/blob/de7cd3642ba312628bafe412857d7518c91d003e/deployments/deployment.yaml#L150
> config: fix content-sources deployment name

- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
Image builder UI fetches `/composes` and render its data in "All Images" Table.
Following the new blueprint layout, the table has a new column for the corresponding blueprint's version, but the `blueprint_version` field exists only in the specific `blueprints/{id}/composes` endpoint.
> feat(HMS-3587): Add blueprint_version field to /composes

- internal/clients/composer/client.go
- internal/clients/composer/package.go
- internal/clients/content_sources/client.go
- internal/clients/content_sources/package.go
- internal/clients/provisioning/client.go
- internal/clients/provisioning/package.go
This pull request moves the go:generate comment from the client.go file to a separate package.go file for each client. This improves code organization and makes it easier to manage the go:generate commands for each client.
Reason: I skipped review of `client.go` the other day because I thought the file is generated while it is actually not.
I already asked to do the same in https://github.com/osbuild/image-builder/pull/1128 which introduces a 4th client into the codebase.
> clients: move go:generate comment into separate file

- templates/iqe-trigger-integration.yml
Since the trigger gets deployed in the same namespace multiple times, the service account will need to be set per deployment.
> templates/iqe: parametrise service account

- cmd/image-builder-db-test/main_test.go
- internal/db/db_blueprints.go
We just mark the composes as delted, so we need extra query. This makes sure we mark composes for deleted Blueprints as deleted.
> Blueprints: cascade delete of Blueprint to Composes (HMS-3926)

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
If both openscap and subscription customizations are set, we should explicitly add `rhcd` to the list of enabled services. For some reason the service gets disabled during the openscap remediation and is then not running when the system has started.
> v1: explicitly add rhcd for openscap + subscription

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
---
Request from @andrewgdewar, it makes sense, the time part was ignored anyway.
> v1: switch snapshot_date format to extended ISO 8601

- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
- internal/v1/handler.go
- internal/v1/handler_test.go
In #1046 we've forgotten to add the version to the actual response.
Also we have not exposed blueprint id which might be quite useful.
Fixes https://github.com/osbuild/image-builder-frontend/issues/1982
> composes: Add blueprint version to the composes response (HMS-3587)

- internal/clients/recommendations/client.go
The recommendation team is exposing this service and adding proxy configuration with a different URL. Therefore, I'm updating the URL accordingly
> internal/recommendations: fix package recommendation url

- .github/workflows/tests.yml
The script we were using before no longer works, and the results weren't posted for a while now. We should use the v4 action if we want to keep using codecov.
> .github/workflows/tests: remove codecov

- internal/v1/api.yaml
This commit removes the array from the recommendation response, resolving the issue of missing data displayed on the frontend.
> v1: Fixed recommendation response schema

- cmd/image-builder/logging.go
- internal/common/echo_logrus.go
Implements fields in addition to the context
for better errors context in tools like glitchtip
Please comment on
* what are your thoughts on using fields or context
* should we try to generalize errors (not including dynamic things like path, method,… as "text")
When using this I think tools like glitchtip can be more useful, although readability in the plain logs might suffer:
before
```
time="2024-05-02T15:19:39Z" level=debug msg="Started request GET /api/image-builder/v1/composes/fc4b8a3d-3ded-4a50-847d-5d1a5daa4483" func=main.requestIdExtractMiddleware.func1 file="/go/src/github.com/osbuild/image-builder/cmd/image-builder/logging.go:76" insights_id=FITVV1Rw5Mk0 request_id=qgyuWGSPHGge
```
after
```
time="2024-05-03T10:10:51Z" level=debug msg="Started request" …
```
> echo_logrus: implement adding fields

- .github/workflows/spec-update.yml
- .github/workflows/tests.yml
- go.mod
- go.sum
- tools/prepare-source.sh
With RHEL 9.4 there is now UBI9 with Go 1.21, let’s upgrade. In fact, we could take advantage of `slices.Contains` introduced in 1.21 in another PR right away.
This PR contains bump to 1.21 and go dependencies bump to latest versions.
> build: bump Go to 1.21

- cmd/oscap/main.go
- internal/v1/handler_compose_image.go
Since we have upgraded to go v1.21 we can now make use of the `slices.Contains` function which checks to see if a slice contains a particular element. This commit switches all custom implementations of the `slices.Contains` function.
> multi: use `slices.Contains`

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
- internal/v1/server.go
this commit add optional target to composeBlueprint endPoint that bring the ability
to build image with specific image types, also add support at the handler function
add unit tests that check this changes
> v1: add targets to the composeBlueprint endPoint (HMS-4066)

- pr_check.sh
The actual image build can take up to 60 minutes and there is not enough time for the rest of the tests and cleanup then.
> pr_check: Increase timeout to 90m

- internal/v1/handler_blueprints.go
Read a special header that only our UI sends to distinguish UI and API requests.
> v1/api: Read extra header to distinguish UI requests (HMS-4254)

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints_experimental.go
- internal/v1/handler_blueprints_test.go
Add non-experimental version of Blueprints endpoints.
Add wrappers for experimental endpoints, so we can serve both.
Wrappers will be removed once ready in #1204
Good opportunity for an API re-review :)
> v1/api: move blueprints endpoints out of experimental (HMS-4200)

- cmd/image-builder/logging.go
- cmd/image-builder/main.go
- internal/common/echo_logrus.go
This is a followup of https://github.com/osbuild/image-builder/pull/1171/files
I have couple of concerns with the recent changes.
* The new fields are only present when echo logger is used. There are many other logs created through logrus interface (e.g. all SQL queries done by the pgx driver) which will miss all those fields.
* All path params are added and can possibly override existing fields e.g. msg or level. This could have unwanted effects, this new patch protects the most important fields. (I haven’t tested this chances are logrus would not allow overriding level or msg fields at all.)
* There were concerns about memory consumption or performance - `logrus.Fields` is a map and context is a lightweight object by design. Paths typically contain one or two fields maximum, with path …
> echo_logrus: use std context for fields

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
Adds snapshots to 3rd party repos.
- Payload repositories and custom repositories are resolved separately, since the UI passes them in separately as well.
- ~~The 'base' repositories have their dnf repo config added to /etc as well, this way users can get all content from consoledot.~~ After further discussion with @jlsherrill we decided to just leave it for now, and if users subscribe and run dnf update they'll get the latest content again.
> Snapshots for 3rd party repos (HMS-4260)

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
The content-sources api is switching to RFC3339.
> v1: switch to RFC3339 when querying snapshots for a date (HMS-4351)

- distributions/rhel-10-nightly/rhel-10-nightly.json
Depsolving fails on ssl verification.
> distributions: switch to http urls for rhel-10-nightly

- cmd/image-builder/logging.go
- cmd/image-builder/logging_test.go
- cmd/image-builder/main.go
- internal/clients/composer/client.go
- internal/common/context.go
This pull request updates the code to pass the external id into the composer. It also includes changes to the common package to handle request ids and insights request ids.
Requires this feature to be present in composer:
https://github.com/osbuild/osbuild-composer/pull/4047
Will work without any problems with old composer versions.
> common: pass external id into composer

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
They require extra setup, like subscribing and pointing to mTLS certs.
> v1: disable custom repositories' snapshotted repos in repo config

- internal/v1/handler_blueprints_test.go
this commit add checks in several tests to skip them when running on macOS (darwin) 
using `runtime.GOOS == "darwin"` 
this prevents the tests from failing on macOS since the `crypt()` function is not supported on this platform.
> internal/v1: Skip crypt() tests on macOS

- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
- internal/v1/handler.go
- internal/v1/handler_test.go
- this commit add unit test for GetComposeStatus handling 404 NotFound response`composeStatus` doesn't found
- Added TestGetComposeStatusNotFoundResponse to cover the scenario where the compose status API returns a 404 NotFound response, improving the function's test coverage.
- Renamed a test to better reflect the specific case it covers.
increase the coverage of GetComposeStatus  from  *62.2%* to *70.3%*
> tests: add more coverage to composeStatus unit tests

- .github/workflows/tests.yml
- cmd/image-builder/main.go
- go.mod
- go.sum
- internal/config/config.go
- internal/v1/server_test.go
- templates/image-builder.yml
- vendor/github.com/osbuild/osbuild-composer/pkg/splunk_logger/environment_hook.go
- vendor/modules.txt
add deployment channel as field to the logs similar to 
https://github.com/osbuild/osbuild-composer/pull/4285
and based on
https://github.com/osbuild/osbuild-composer/pull/4301
> cmd/image-builder: add deployment channel as field to the logs

- internal/v1/server_test.go
Instead of string comparing use the http.ErrServerClosed when checking for echoServer.Start()
> server: use error type ErrServerClosed in test

- internal/v1/handler_blueprints_test.go
- internal/v1/handler_get_compose_status_test.go
- internal/v1/handler_post_compose_test.go
- internal/v1/handler_recommend_package_test.go
- internal/v1/handler_test.go
- internal/v1/server_identity_test.go
- internal/v1/server_test.go
tests: tweak tutil to take `addr` and `path` instead of url
This commit avoids the hardcoded URL and uses the addr that the
echo server is using. This makes it easier to run the tests on
a different port.
Mostly auto-generated via `sed` (unfortunately some manual tweaking
was needed because the coding style is not very consistent).
> tests: tweaks to the way routes are tested

- templates/image-builder.yml
CHANNEL has to be specified as parameter to get filled
otherwise it's literally `${CHANNEL}` :-|
followup of #1299
> templates/image-builder: add CHANNEL as parameter so it get's filled

- .github/workflows/tests.yml
this commit enable codecov to be able to see the updated coverage
this issue https://github.com/codecov/feedback/issues/354 was fixed
> test: enable codecov to be able to see the updated coverage

- distributions/centos-10/centos-10.json
- distributions/rhel-10-nightly/rhel-10-nightly.json
These were added by [1], so let's enable them in the service.
There are no GCP guest tools repos for c10s / el10 yet, so use those from el9 for now.
Also update the RHEL-10-nightly repos to non-Beta URLs, since those already contain composes.
[1] https://github.com/osbuild/osbuild-composer/pull/4314
> c10s/el10: support gcp and image-installer img types

- internal/v1/handler_test.go
This commit add unit test for `getComposeStatus` handling the StatusInternalServerError response after composeStatus found.
Increase the coverage of GetComposeStatus from *70.3%* to *83.8%*
> tests: add more coverage to composeStatus when response is InternalServerError

- internal/v1/handler_test.go
* this commit add unit test for `GetCloneStatus` handling 404 notFound response cloneEntry doesnt found
* increase the coverage from 48% to 54.1%
> tests: add coverage to `GetCloneStatus` unit test

- codecov.yml
Generating a new comment seems fine, but I guess generates too many E-Mail which might get annoying.
So we'll try this behavior and the footer also seems not necessary
> codecov.yml: change codecov to avoid new comments

- Makefile
- cmd/image-builder/main.go
reporting the git hash in the logs should ease the search which version exactly is deployed
any thoughts on this (or how to really verify the deployed version or if the deployment is still ongoing)
> Makefile/Dockerfile-ubi: implement logging git hash

- internal/clients/compliance/client.go
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
There's only a single tailoring item per rhel minor version per policy, and
you can index the tailorings by id or by rhel minor version.
---
The tailoring id was hardcoded and the test didn't catch it because it was the same id as the hardcoded one in the test :facepalm:
> clients/compliance: use minor version instead of tailoring id

- internal/v1/server_test.go
The current implementation just creates a "failed test" entry (e.g. if the port is in use) and continues testing
I had the problem again of some other debug service running and the error (of port in use) was lost in console output
> internal/v1/server_test.go: cancel tests on failed test server

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
EnsureParents doesn't actually work on files, so create the directory first.
---
Adding the directory customisation in manually makes it work!
> v1: create directory before inserting openscap tailoring data

- internal/clients/composer/client.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler.go
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
- internal/v1/handler_get_compose_status_test.go
- internal/v1/handler_post_compose_test.go
HMS-4562
See the issue for detailed acceptance criteria, in short the PR:
> (HMS-4562) Allow Blueprints update without changing User password

- internal/clients/composer/openapi.v2.gen.go
- internal/clients/composer/openapi.v2.yml
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
The policy ID will be added to the RHSM facts, allowing the compliance service to tie instances to the specified compliance policy.
> v1: add policyID to compose request to composer

- templates/image-builder.yml
This should allow us to track the usage of the first boot script feature.
I looked into the json request and what we're interested in the most is probably the path. While we can almost rule out that a lot of customers are using the files customization (because overall API usage is low) and therefore our data wouldn't be skewed too much, it'd be great to limit the results we account for to `/etc/systemd/system/custom-first-boot.service`
Or would it be more efficient/reliable to use the services customization to check for `"custom-first-boot"` in `enabled`?
> floorplan: Export files customization

- internal/clients/composer/package.go
- internal/clients/content_sources/package.go
- internal/clients/provisioning/package.go
- internal/clients/recommendations/package.go
- internal/v1/server.go
- tools/prepare-source.sh
Unsure how to implement pinning effectively for vendored projects. What I usually do is manually `go get` those libraries in a prepare script or Makefile.
> build: pin oapi-gen until toolbox gets 1.21.13

- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
Return correct status on non-existent blueprint for blueprint/<id>/compose endpoint.
> v1/handlers: Return 404 correctly when Blueprint not found (HMS-4243)

- .gitignore
- Makefile
This commit introduces a new 'coverage-report' target to the Makefile, enhancing the developer's ability to analyze code coverage directly from the terminal.
The new target allows developers to:
- Generate a comprehensive coverage report for the entire project
This addition streamlines the code coverage review process, enabling developers to quickly focus on particular areas of interest within the codebase.
> Makefile: Add coverage-report target

- cmd/oscap/main.go
Trying to fix for gosec:
https://github.com/osbuild/image-builder/pull/1359
This is a manual command, so should by fine (TM).
> cmd/oscap: tigthen file permissions

- internal/v1/handler_recommend_package.go
This error is cluttering glitchtip there are over 2k events and counting. This does not need to be an error:
> v1: empty recommendation is warning now

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
Corrects the name to match the repo name in the cs service, and the URL to point to the cert.console endpoint rather than the internal one.
> v1: fix yum configs of snapshot repositories (HMS-4784)

- templates/image-builder.yml
We currently don't export the subscription customization.
We need this in order to properly count how many images have Insights and rhc enabled.
> floorist: Export subscription customization

- renovate.json
The renovate.json file determines how often Konflux will open PRs to update the tekton configs.
See #1366.
> renovate.json: configure Konflux updates

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
Default repositories that don't require RHSM don't have the guarantee of having snapshots. So just pick latest for those repositories.
The only relevant case at the moment is the google cloud tooling for the GCP image types.
> v1: fix GCP images with snapshots (HMS-4830)

- test/cases/api.sh
It seems that network error can cause the whole pipeline to fail just because an unsuccessful registration. Let’s try it one more time if that happens.
> test: rhsm unregister fallback call

- .github/workflows/tests.yml
- Makefile
- tools/dbtest-entrypoint.sh
- tools/dbtest-run-migrations.sh
In the endeavor to implement pruning the customer data after two years (see https://issues.redhat.com/browse/HMS-4244 )
We first implement running the DB test locally by spinning up a container with postgres.
This is as close as possible to the implementation in the github action and enables to develop more DB tests and execute them.
Also changed here: `image-builder-db-test` is not compiled and run, but just executed as test, as we don't really need the binary
> Makefile: implement running DB tests locally

- internal/oauth2/lazy_token.go
- internal/oauth2/lazy_token_test.go
- vendor/github.com/sirupsen/logrus/hooks/test/test.go
- vendor/modules.txt
Avoid printing the token to the logs
> internal/oauth2/lazy_token: avoid printing the token to the logs

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_compose_image.go
When adding a user, immediately add it to the specified groups.
---
It should be fine to drop the default as the edge-api always adds the groups already
https://github.com/RedHatInsights/edge-api/blob/622244f04989159709332e67788c04296989e431/pkg/clients/imagebuilder/client.go#L353-L358
> v1: expose groups in user customization (HMS-4901)

- pr_check.sh
We don't have any tests marked for parallel execution.
> pr_check: Disable IQE parallel execution

- cmd/image-builder-maintenance/config.go
- cmd/image-builder-maintenance/db.go
- cmd/image-builder-maintenance/db_test.go
- cmd/image-builder-maintenance/main.go
- templates/maintenance.yml
The main table to delete data from, is actually "composes".
Data in the "clones" table is deleted implicitly.
> image-builder-maintenance: fix typo in variable name

- templates/image-builder.yml
fixes typo in image-builder sql statement…
Just came across the error in the logs
```console
cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "b"
LINE 5: b.metadata->>'is_on_prem' as is_on_prem
^
[SQL: select
v.blueprint_id::text as blueprint_id, v.version, b.deleted,
b.metadata->>'exported_at' as exported_at,
b.metadata->>'parent_id' as parent_id
b.metadata->>'is_on_prem' as is_on_prem
from
blueprint_versions v
left outer join blueprints b ON v.blueprint_id = b.id]
(Background on this error at: https://sqlalche.me/e/20/f405)
```
> templates/image-builder: fix typo in image-builder sql statement

- internal/v1/handler.go
this commit improve error handling and code structure
* Split GetComposeStatus into smaller, more focused functions
* Enhance error handling with more specific HTTP status codes *Add dedicated functions for handling different response scenarios
* Implement parseAndRedactComposeRequest for better separation of concerns
* Improve code readability and maintainability
> v1/internal: refactor `GetComposeStatus` improve error handling 

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
Addition to #1252
This switches the snapshot date from a DateOnly format to RFC3339 in one more place.
> internal: Switch snapshot date to RFC3339

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
This adds back support for DateOnly format of snapshot dates.
> internal: Support both DateOnly and RFC3339 format for snapshot dates

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
- internal/v1/mocks/content_sources.go
If a gpg key is not added, the content sources api will still return an empty string. Composer cannot deal with an empty, not-nil gpg key, so just ignore the key in this case.
JIRA: [HMS-5310](https://issues.redhat.com/browse/HMS-5310)
> v1: ignore empty, not-nil gpg keys from content sources (HMS-5310)

- internal/distribution/distroregistry.go
Just fixing typo introduced in https://github.com/osbuild/image-builder/pull/1473
> fix: distribution comment typo

- Makefile
- README.md
We'll avoid the name "image-builder" here, as this repository is now renamed to `image-builder-crc` and the command line interface tool and RPM is called `image-builder` which would cause confusions at least in the overarching documentation in osbuild.org.
See: https://github.com/osbuild/image-builder-cli
There are more places which might cause confusions like the binary is also called `image-builder`
https://github.com/osbuild/image-builder-crc/blob/4ecc6263f1f07d8617a52777fe45c03ed5b43987/Makefile#L24
…but that's up to followup PRs
> Docs: Reword README and Makefile-comment to avoid "image-builder"

- .github/workflows/tests.yml
- tools/prepare-source.sh
There is something different on the CICD, I am unable to reproduce this failure locally:
https://github.com/osbuild/image-builder-crc/pull/1490
This is an attempt to fix that. Versions do vary, this puts them in sync.
> build: ensure Go version in prep script

- internal/clients/content_sources/util.go
- internal/clients/content_sources/util_test.go
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
Whenever snapshot URLs are used, they need to be used with the internal URL, as it's content hosted by content sources.
> clients/content_sources: fix baseurl for upload repositories

- README.md
For better orientation of users, this link should point to the deployed version of image builder.
> README: improve link to console.redhat.com

- tools/prepare-source.sh
I do not understand why PRs are failing on the prepare script: https://github.com/osbuild/image-builder-crc/actions/runs/13613898854/job/38054492007?pr=1501 (and many more this week).
The [line is already there](https://github.com/osbuild/image-builder-crc/blob/main/go.mod#L54) in main. Something is not right.
Just trying something in this PR.
> build: make sure tools are in go.mod

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
This arose from a misunderstanding in osbuild/image-builder-crc#1283,
the compose request that is sent to osbuild-composer shouldn't be
considered as a user-facing endpoint, and omitting the password before
sending it off will result in no password being set at all.
> v1: don't redact password when starting a compose

- cmd/image-builder/main.go
- internal/oauth2/lazy_token.go
Tracing was explicitly disabled, this flag lift up tracing being added to context, it can be now distributed through the app and correlation will start. Remember, you can use `trace_id` field to trace ALL messages from now on, the tracing random string is also returned via HTTP header and passed in called services (e.g. composer) via HTTP header too.
The patch also drops a very noisy debug line "reusing token" which appears way to often to my taste and carries low informative value.
> fix: remove trace disallow flag

- templates/image-builder.yml
In order to track the locale and timezone features in our metrics report, we need to export the usage of these customizations via Floorist.
> floorist: Add locale and timezone to query

- internal/v1/handler_blueprints.go
Uninitialized slices marshal into `null` instead of an empty array.
> v1: avoid returning null in blueprint lint section

- internal/common/testdata/exported_blueprint.json
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
The front-end needs to know whether or not a user has a password so that
it can correctly render the password input field in edit mode. If there
is no password, the field should be empty. If there is a password, a
placeholder similar to '********' will be displayed.
>  v1: add hasPassword field to user

- templates/image-builder.yml
Parquet doesn't deal well with empty objects:
```
Cannot write struct type 'timezone' with no child field to
Parquet. Consider adding a dummy child field.
```
Work around it by returning 'null' if all the fields in the objects are marked as optional.
> templates/image-builder: fix floorist query

- internal/v1/server_test.go
The test logs are actually quite hard to read in case of failures, they obscure useful information.
--- 
Similar to https://github.com/osbuild/osbuild-composer/pull/4614, might be controversial so depending on what other people think. But generally the useful information is in that which go test outputs, not the logs.
> v1/test: discard all log output

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
- internal/v1/mocks/content_sources.go
Tested the recent [backend changes for content templates](https://github.com/osbuild/image-builder-crc/pull/1489) in the associated frontend PR and am hitting this [error](https://github.com/osbuild/image-builder-crc/blob/main/internal/v1/handler_compose_image.go#L161) when composing an image using a template. 
I'm not sure if the request is failing due to the missing base RH repositories, but they need to be added regardless.
> v1: fix adding RH repos from template to compose request

- renovate.json
Fixes: https://github.com/osbuild/image-builder-crc/issues/1559
> renovate.json: fix syntax error

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
We need to use the internal pulp URL for RH repo snapshots coming from a content template so composer can access it, otherwise we'll see errors reading the repository on image build
> v1: use internally accessible baseurl for RH repo snapshot from template

- renovate.json
Currently the bot is trying to update the go version of the whole project (see #1562), but the max go version at any given time should be the one shipped in the ubi9 go-toolset container.
> renovate.json: pin go version

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
Sets RHSM to false for repository snapshots coming from a template. When set to true, the RHSM certs would be used instead of the service account certs which may have resulted in repository read errors when building an image with a template.
> v1: set rhsm to false for repo snapshots from template

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
We want to allow creation of system users with `/sbin/nologin` shell.
Not sure how to link jiras so trying both what I have seen so far:
https://issues.redhat.com/browse/HMS-4181
/jira-epic HMS-4181
JIRA: [HMS-5993](https://issues.redhat.com/browse/HMS-5993)
> v1: allow users without pass/key (HMS-5993)

- internal/v1/handler_compose_image.go
Initialize custom repos before assignment when building with a content template so they are omitted from the compose request
> v1: omit empty custom repos from compose request

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
- internal/v1/mocks/content_sources.go
Similar to this [PR](https://github.com/osbuild/image-builder-crc/pull/1578), if we build an image with a template that has no custom repositories, the payload repositories will be empty so we need to omit them correctly from the compose request.
> v1: omit empty payload repos from compose request

- cmd/image-builder/main.go
- internal/config/config.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
- internal/v1/server.go
- templates/image-builder.yml
Value of the environment variable INSIGHTS_CLIENT_PROXY is passed along to composer. Depends on this work: https://github.com/osbuild/osbuild-composer/pull/4672
Feedback welcome and appreciated :)
JIRA: [HMS-5992](https://issues.redhat.com/browse/HMS-5992)
> v1: Add InsightsClientProxy to compose request (HMS-5992)

- internal/v1/handler_oscap.go
Enable oscap customizations for some missing rhel9 distros and for rhel10
> oscap: add missing rhel9 and rhel10 distros

- internal/tmpl/aap-first-boot.tmpl.service
- internal/v1/handler_post_compose_test.go
There was a copy & paste error and the `[Unit]` header was missing from the service file.
> v1: aap service file missing header

- internal/clients/composer/openapi.v2.gen.go
- internal/clients/composer/openapi.v2.yml
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
If a template is being used, the template name or UUID is sent in the compose request for system registration. If the RHEL version is >= 9.6, the name is used for registration. Any older version uses the UUID for registration.
JIRA: [HMS-6297](https://issues.redhat.com/browse/HMS-6297)
> v1: send template uuid/name in compose request (HMS-6297)

- internal/v1/api.yaml
This is a minor fix but the example uses a hostname and not the full url.
> v1: app change aap controller url example

- internal/v1/handler_compose_image.go
This fixes a small issue the registering on boot for RHEL 10, when building from a template. When registering to insights, systems buit with RHEL 10 images (or higher) must use the template name.
> v1: pass template name in compose request for RHEL 10

- internal/v1/handler.go
For consistency, make the logged message all lowercase. In addition, make the message shorter, since the additional information is captured in the code comment.
> internal/v1: improve a logger warning message (HMS-6016)

- internal/common/pagination.go
- internal/common/pagination_test.go
- internal/v1/handler.go
Small nitpicks for the paginator, mostly docs, inconsistency for getters (some having the prefix while others dont) and useless memory consumption for count.
It is worth noting that in the review (https://github.com/osbuild/image-builder-crc/pull/1610) I expressed an opinion to avoid getters for the fields alltogether and export all the three fields. The type currently is mutable due to the fact that it does not copy the slice, so exposing those fields does not change a thing about immutability. However, type inference for generics only works with functions, so it would create it a little more verbose which I do not like:
```go
p := common.Paginator[int]{values, limit, offset}
```
Therefore I am not including such a change.
> refactor: add documentation to paginator

- .github/workflows/gobump.yml
Since gobump proven to be useful in `images`, I am proposing it for composer as well. We would drop other dependency bots and only use gobump. It bumps weekly.
This can only be tested after GHA exists and then it can be triggered against `upstream` branch manually to fine-tune it. It is the exact copy from `images` job: https://github.com/osbuild/images/blob/main/.github/workflows/gobump.yml
Also filed: https://github.com/osbuild/osbuild-composer/pull/4758
> ci: introduce gobump gha

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
For now we won't differentiate between possible local or hosted MCP deployments.
Still can be used for metrics UI / API vs MCP.
> Support MCP clientId for metrics

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_compose_image.go
Add support for the new Disk (advanced partitioning) customizations to the API by directly importing the type from the osbuild-composer cloud API.
I initially [copied the types to the API yaml directly](https://github.com/achilleas-k/image-builder-crc/blob/df26e9a9af8c5396de1cd32410a9d7dc8d1fa3ee/internal/v1/api.yaml#L2366C5-L2503), which created  bunch of changes to existing variables in the generated code.  That was fine, easy to update all references to work.  The problem is that it becomes [a bit of a pain to convert from one to the other](https://github.com/achilleas-k/image-builder-crc/blob/df26e9a9af8c5396de1cd32410a9d7dc8d1fa3ee/internal/v1/handler_compose_image.go#L1341-L1415), because of the way the union types work.
I also tried [converting via …
> Add support for Disk customizations

- renovate.json
Gobump is also enabled, and it can limit go version upgrades.
> renovate.json: disable gomod manager

- cmd/image-builder/main.go
- internal/config/config.go
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
- internal/v1/server.go
- templates/image-builder.yml
PatchURL is loaded in from the environment and passed down the compose request when registering on-boot with a template for RHEL <= 9.5. It is required for system registration.
related: https://github.com/osbuild/osbuild-composer/pull/4756
jira: https://issues.redhat.com/browse/HMS-8558
> v1: add PatchURL to compose request

- distributions/rhel-9.6/rhel-9.6-aarch64-appstream-packages.json
- distributions/rhel-9.6/rhel-9.6-aarch64-baseos-packages.json
- distributions/rhel-9.6/rhel-9.6-x86_64-appstream-packages.json
- distributions/rhel-9.6/rhel-9.6-x86_64-baseos-packages.json
- distributions/rhel-9.6/rhel-9.6-x86_64-google-cloud-sdk-packages.json
- distributions/rhel-9.6/rhel-9.6-x86_64-google-compute-engine-packages.json
- distributions/rhel-9.6/rhel-9.6.json
895479b0066d5c3fe43a8f83c7e1bdf2624dfe8c mentioned that the package lists are not needed because the frontend is now fully switched to use the content service but we missed a piece: the edge service still uses the package search provided by us.
This commit thus generates the package lists for 9.6 to fix the edge-mgmt service. I ran the following command:
./tools/generate-package-lists \
--distro distributions/rhel-9.6/rhel-9.6.json \
--key /etc/pki/entitlement/ID-key.pem \
--cert /etc/pki/entitlement/ID.pem
Note that generating the package list for RHEL 10.0 isn't necessary because edge-mgmt doesn't supprot RHEL 10
> distributions: generate package lists for rhel-9.6

- internal/common/testdata/exported_blueprint.json
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
AAP was in image_request, but since it is not an extra registration and more a firstboot, I moved it to customizations. Also edited tests for import and export.
Just one question - do I understand correctly that when exporting a bp, we want to redact certificates (I also removed config key), but when importing, we expect the user to have the certificates in the request? In my head it made sense, so hopefully that's ok :)
> AAP: import/export (HMS-8836) (HMS-8837)

- .github/workflows/tests.yml
This fixes broken CI:
```
./test/cases/api.sh:29:1: note: This function is never invoked. Check usage (or ignored if invoked indirectly). [SC2329]
./test/cases/api.sh:48:1: note: This function is never invoked. Check usage (or ignored if invoked indirectly). [SC2329]
```
Created an issue to unpin it or upgrade it: https://github.com/osbuild/image-builder-crc/issues/1666
> gha: pin shellcheck to 0.10

- distributions/fedora-43/fedora-43.json
- distributions/fedora-44/fedora-44.json
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_test.go
We need these to build the runners to start building and testing osbuild RPMs.
> distributions: add Fedora 43 (branched) and 44 (rawhide)

- cmd/image-builder/main.go
- internal/v1/server.go
- internal/v1/server_identity_test.go
main: use echo middleware with context
New function NewEchoV4MiddlewareWithConfig is utilized to use native
echo middleware which prevents incorrect error logging.
New function NewProxyWithContextFor allows for setting request-based
context-aware logger for echo logger. This will include all correlation
fields to be inluded in all echo log records.
Middleware was moved from main.go to server.go and identity extraction
was put as the first middleware to be done as soon as possible so all
logs will include the relevant context.
Logging configuration was updated with ContextCallback that puts
organization id (and fedora user) in all log/slog lines automatically.
---
The first commit updates the `logging` library to v0.0.5 which requires the necessary features.
The second commit contains …
> Update logging & native middleware & context improvements

- .github/workflows/gobump.yml
I added a new feature to gobump - every update will now come with a changelog. Due to size, these will be links to gists for each PR. Example: https://gist.github.com/lzap/b46a70514be80685d9e1b9a041dfdb5c
> ci: enable changelog for gobump

- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
- internal/db/db_blueprints.go
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
There are certain scenarios where the account number isn't set in the identity header. For instance when using service accounts and working via the api, the account number will be empty. Deleting the same blueprint via the UI will fail because there the account number will be set.
> db: only match on org id when deleting blueprints (HMS-9329)

- templates/image-builder.yml
In order to assess how much the `AWS clone to region` feature is used, let's take a look at the numbers.
(This feature was a pre-requisite for the - now decommissioned - 'Launch in AWS' feature. It's not useless now, but also just a convenience function.)
> floorplan: Dump clones table (HMS-9078)

- templates/image-builder.yml
in 5433c6b we've used incorrect (old) repo. We have switched to a new repo in the meantime.
Ugh, someone made an oopsie in #1699
> clowdapp: Use correct Konflux image

- internal/v1/handler_compose_image.go
Because `rhcd` is no longer used in RHEL 10, enabling it causes RHEL 10 builds to fail.
The `rhcd` service is enabled for images that have an OpenSCAP profile. This customization does not appear in the blueprint, rather it is injected into the compose request.
This commit removes this behavior for RHEL 10.
We should also revisit enabling rhcd altogether in the future. It is probably an antipattern. Consider:
1. What happens if a user explicitly masks or disables rhcd?
2. Should we even be doing this? We don't know why we need to do this.
3. If we do need to do this, shouldn't this knowledge live in osbuild/images?
> v1/internal: Do not enable rhcd service for RHEL 10 (HMS-8756)
