- templates/README.md
- templates/image-builder.yml
These are needed for deploying into cloud.redhat.com's OpenShift.
> Add OpenShift templates

- templates/image-builder.yml
Apparently dealing with integers in OpenShift template YAML is a pain.
> Explicitly set listening port without variables

- templates/image-builder.yml
Update the service name and port to match the 3scale setup.
> openshift: Update template to match 3scale configuration

- .github/workflows/container.yml
From a good suggestion from @larskarlitski. 😉
> Run prepare-source.sh in github workflows

- templates/image-builder.yml
I want to see if the changes in app-interface worked, i somehow can't see the secrets directly, so I'm not actually sure if they're in place.
> templates: Add database secrets to container environment

- distribution/openshift-startup.sh
> 🤷 openshift: Fix CW var in bash script

- .github/workflows/gosec.yml
- internal/server/distribution.go
- internal/server/server.go
> 🔍 Run gosec static analyzer

- .github/workflows/tests.yml
- README.md
- internal/server/distribution.go
- internal/server/server.go
This should be merged before #61
> Unit tests and coverage

- .github/workflows/tests.yml
- schutzbot/build.sh
- schutzbot/provision-composer.sh
- schutzbot/run_tests.sh
this yields lots of issues and I'm not sure if I should follow all of the suggestions to resolve them or not.
> tests: Enable shellcheck

- templates/image-builder.yml
> templates: Add osbuild-composer secrets to deployment

- internal/server/server_test.go
> Tests for ComposeImage

- templates/image-builder.yml
> Fix indentation in osbuild-composer deployment

- templates/image-builder.yml
> Fix volumes indentation

- templates/image-builder.yml
> 🔌 Connect image-builder to composer in AWS

- templates/image-builder.yml
> ✏ Update comment to reference AWS

- distribution/openshift-startup.sh
Let's start doing this when the database PR is in.
> distribution: Remove db variables echo from startup script

- README.md
> Add test steps into README

- .github/workflows/tests.yml
- schutzbot/send_webhook.py
I'm not sure if there's a reason for security concern here, do we need specific branch protections or other repo settings for this ?
> schutzbot: ⚡Trigger schutzbot using github actions

- cmd/image-builder-tests/main_test.go
- internal/cloudapi/client_test.go
- internal/cloudapi/cloudapi_types.go
- internal/cloudapi/cloudapi_types.yml
- internal/server/api.go
- internal/server/api.yaml
- internal/server/server.go
- internal/server/server_test.go
- schutzbot/provision-composer.sh
The composer-api endpoint to fetch the status of an image build changed. This PR is meant to adapt to this.
> server: Adapt to new ComposeStatus from composer

- distributions/fedora-32.json
- distributions/rhel-8.json
- tools/generate-package-lists
Started out in bash but this was so much easier to get right
> tools: Add helper script for dnf-json

- cmd/image-builder-tests/main_test.go
- cmd/image-builder/config.go
- cmd/image-builder/main.go
- distributions/centos-8.json
- distributions/fedora-32.json
- distributions/rhel-8.json
- internal/cloudapi/cloudapi_types.go
- internal/cloudapi/cloudapi_types.yml
- internal/server/api.go
- internal/server/api.yaml
- internal/server/distribution_test.go
- internal/server/server.go
- internal/server/server_test.go
- schutzbot/provision-composer.sh
- templates/image-builder.yml
> server: Add support for gcp target

- internal/server/server_test.go
This should address #142 
---
consecutive successful runs: 
- https://github.com/osbuild/image-builder/pull/144/checks?check_run_id=2021161266
- https://github.com/osbuild/image-builder/pull/144/checks?check_run_id=2021180909
- https://github.com/osbuild/image-builder/pull/144/checks?check_run_id=2021357543
- https://github.com/osbuild/image-builder/pull/144/checks?check_run_id=2021578074
- https://github.com/osbuild/image-builder/pull/144/checks?check_run_id=2021691879
> server: Wait until server is up in unit tests

- image-builder.spec
- schutzbot/Jenkinsfile
Two things:
- remove some bit-rotten stuff from Jenkinsfile
- Move the tests from Fedora 32 to Fedora 33
> Schutzbot clean-ups

- internal/server/api.go
- internal/server/api.yaml
- internal/server/server.go
Expose /ready at /api/v1/image-builder.
> server: expose /ready route

- internal/cloudapi/cloudapi_types.go
- internal/cloudapi/cloudapi_types.yml
- internal/server/api.go
- internal/server/api.yaml
- internal/server/server.go
- internal/server/server_test.go
- schutzbot/deploy.sh
- test/cases/api.sh
Change imageRequest to accept a single uploadRequest instead of
an array of uploadRequests.
> cloudapi: single uploadrequest

- templates/image-builder.yml
Fix duplicate container names, and map the db secrets for the main
container.
> templates: DB related fixes

- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
This version just shows the amount of compose requests and the amount of
compose 500s.
> templates: Commit initial version of dashboard

- internal/server/server.go
> server: buildCustomizations never returns an error

- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
I also added a variable selecting the range. Followup of #186
> dashboards: Adapt to simple counters

- schutzbot/Jenkinsfile
- test/cases/api.sh
Add subscription test case and add environment to CI.
> Add subscription test case in aws and gcp

- test/cases/api.sh
To resolve the subscribe check random fail issue(#199).
> Loop check subscribe status

- test/cases/api.sh
> test: Increase subscription check timeout / disable -e and -u flags

- test/cases/api.sh
1. Boot up Azure VM and check image
2. Delete os_disk, NIC, public-ip, nsg, vnet, image and blob in cleanupAzure.
> Add Azure boot up test and clean up Azure resources after test

- internal/server/prometheus.go
The numbers didn't make any sense, this is why :)
> prometheus: Measure elapsed time at the end of handling the request

- distributions/centos-8-x86_64-packages.json
- distributions/centos-8.json
- distributions/rhel-84-x86_64-packages.json
- distributions/rhel-84.json
- internal/cloudapi/client_test.go
- internal/server/distribution_test.go
- test/cases/api.sh
Added Ansible to the list of available packages for anyone building rhel 8.4 images.
Jira ticket: https://issues.redhat.com/browse/COMPOSER-981 
In order to keep CentOS 8 Streams as close as possible to rhel, ansibile has also been added to CentOS. 
TODO:
> Added ansible to the rhel 8.4 distribution files.

- internal/v1/server_test.go
The function GetComposeMetadata in server.go is not covered. With this PR we add a unit test to it.
> [QE] add unit tests for GetComposeMetadata

- schutzbot/deploy.sh
Exit 1 in case this fails. We always want to test IB against the current
version in stage.
> schutzbot: Always grab versions from terraform repo

- .github/workflows/container.yml
- .github/workflows/coverity.yml
- .github/workflows/gosec.yml
- .github/workflows/tests.yml
- .github/workflows/trigger-gitlab.yml
Update dependencies related to github actions
> Update github actions dependencies

- .github/workflows/tests.yml
- .gitignore
- Makefile
- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
- internal/db/migrate.go
- internal/db/migrations/2_alter_table_rename_account.down.sql
- internal/db/migrations/2_alter_table_rename_account.up.sql
- internal/tutils/tutils.go
- internal/v1/server_test.go
Let's avoid confusion, account_numbers are actually shared.
Fixes #242
> db: Rename account_id to account_number

- cmd/image-builder-db-test/main_test.go
- cmd/image-builder/main.go
- internal/common/quota.go
- internal/config/config.go
- internal/db/db.go
- internal/db/migrations/1_create_table_images.down.sql
- internal/db/migrations/2_alter_table_rename_account.down.sql
- internal/db/migrations/3_add_alter_table_composes.down.sql
- internal/tutils/tutils.go
- internal/v1/server.go
- internal/v1/server_test.go
- schutzbot/deploy.sh
- templates/image-builder.yml
- test/cases/api.sh
This commit introduces a new method to search for composes made a by a
user for a given time period. This adresses the first part of the
issue #247
> DB: search for composes for a time period

- internal/v1/server_test.go
Added basic tests to GetComposes function on server.go
> test: basic unit tests for GetComposes

- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
Simple version bump, as suggested by app-sre onboarding.
> templates: bump dashboard version

- internal/v1/server.go
Currently we are only logging and recording metrics for internal server errors
with exact code 500. This commit now ensures that 5xx errors are logged
and the metrics recorded.
> server: error logging

- .github/workflows/coverity_scan.yml
no need to execute on every merge to main
> ci: Execute Coverity Scan via cron

- internal/common/prometheus.go
- internal/v1/server_test.go
- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
- update prometheus metrics to make use of namespace and subsystem
- update dashboard with new metric names
Note, PR marked as draft since these changes will break alerts and metrics in staging
> Metric namespaces

- schutzbot/build.sh
The official images are in http://quay.io/cloudservices/image-builder
> schutzbot: Expire container images used for testing

- internal/composer/openapi.v2.gen.go
`tools/prepare-source.sh` didn't run on #305.
> composer: Spec update

- README.md
add contributing section to README with link to developer guide
> README: contributing

- internal/composer/openapi.v2.gen.go
- internal/v1/server.go
> internal/composer: Adapt to new spec

- .gitlab-ci.yml
- schutzbot/slack_notification.sh
load test is being executed weekly but has to be reviewed manually. Send
a slack notification with the test result.
> add load test slack notification

- schutzbot/slack_notification.sh
slack notification for load test creates a message with the full link to
the results. Use markdown sintax to shorten the link. Also add the rest
of QE team to the message.
> schutzbot: update slack notificarion

- test/cases/api.sh
scheduled cloud cleaner (running daily on osbuild-composer repo), removes old
enough and tagged resources. Adding the "gitlab-ci-test" tag to all
testing resources so they can get cleaned if the cleanup function fails.
> add test tags to cloud resources

- internal/distribution/distribution.go
> internal/distribution: Make architecture generic

- distributions/rhel-86/rhel-86-x86_64-appstream-packages.json
- distributions/rhel-86/rhel-86-x86_64-baseos-packages.json
- distributions/rhel-86/rhel-86.json
- internal/composer/openapi.v2.gen.go
- internal/v1/server.go
- test/cases/api.sh
- test/cases/edge.sh
- test/data/edge/check_ostree.yaml
The beta repos are now offline, as rhel-86 is GA.
> distributions: Switch to dist repos for rhel-86

- templates/iqe-trigger.yml
This is a template for a tekton job which will trigger IQE test
pipelines on new deployments of image-builder app.
> templates: Add template for iqe-trigger

- templates/iqe-trigger.yml
AppSRE found some issues with this template which are resolved by this
commit.
> templates: remedy iqe-trigger template validation errors

- internal/v1/server.go
- internal/v1/server_test.go
https://github.com/osbuild/osbuild-composer/pull/2636 changed the way
errors are returned. The most relevant error is no longer the top level
error. If the top level error is a dependency failure, return the error
1 level down, recursively.
> v1: Don't return dependency related errors

- .github/workflows/gosec.yml
- internal/distribution/distribution.go
This version fixed a false positive for G307s.
> workflows/gosec: Bump version

- internal/v1/api.go
- internal/v1/api.yaml
Oops, otherwise the new distributions are not usable.
> v1: add fedora-{35-38} to the spec

- templates/image-builder.yml
and use an openshift template variable for flexibility while deploying
>  templates/image-builder.yml: update splunk port for splunk cloud

- internal/v1/handler.go
- internal/v1/server_test.go
closes #385
here is my first draft. Would be nice to get already some feedback on it :)
> treat composer service code 10 as http.status 400

- .github/workflows/spec-update.yml
- .gitignore
- internal/composer/openapi.v2.yml
- tools/prepare-source.sh
- tools/update-spec.sh
example: https://github.com/croissanne/image-builder/actions/runs/3274571733/jobs/5388274669
example pr: https://github.com/croissanne/image-builder/pull/23
---
Fixes #467
> .github: weekly composer spec update workflow

- pr_check.sh
We have merged the frontend and backend plugins to one.
> pr_check: use the new combined iqe plugin

- internal/config/utils.go
- templates/image-builder-clowder.yml
- templates/image-builder.yml
Adds support for parsing cloudwatch config from clowder config.
This reverts commit ece152cce799372ca7bdc3a463e229a1158decfb.
> templates: move to ClowdApp for main deployment

- internal/v1/handler.go
- internal/v1/server_test.go
> internal/v1: return empty array instead of null for collections

- internal/v1/server.go
Reverts osbuild/image-builder#587
> Revert "internal/v1: disable RHEL entitlement check"

- cmd/image-builder-db-test/main_test.go
- internal/composer/client.go
- internal/db/db.go
- internal/tutils/tutils.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler.go
- internal/v1/server_test.go
adding format (for strings), examples, descriptions where needed.
> internal/v1: improve OpenAPI

- internal/v1/handler.go
- internal/v1/server_test.go
This limits the size of AWS and Azure images to 10GiB total per image. The other image types are thinly/dynamicly provisioned, meaning it's fine to not check the limit for those.
HMS-1554
> image-builder: Limit total image size for AWS and Azure

- .github/workflows/spec-update.yml
The wf updates multiple specs now, not just the composer one. Reflect that in the commit message and PR title.
> .github/workflows/spec-update: bump create-pull-request to v5

- templates/dashboards/grafana-dashboard-insights-image-builder-general.configmap.yml
https://grafana.stage.devshift.net/d/image-builder-crc-sanne/image-builder-crc-sanne
> Rework dashboard into API and SLO sections

- internal/composer/openapi.v2.gen.go
- internal/composer/openapi.v2.yml
- internal/provisioning/openapi.v1.gen.go
- internal/provisioning/provisioning.v1.yml
- internal/v1/handler.go
Forgot this when adding them in the API.
> support s3 upload for wsl images

- pr_check.sh
- templates/iqe-trigger-integration.yml
I think this is causing us issues during test that it's not possible to increase the memory fast enough during memory spikes. Need to increase this in order to test that theory.
> templates: Increase memory request for testing

- templates/iqe-trigger-integration.yml
This will enable modification via app-interface saas file.
> templates: parametrize integration test pods resource limits

- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
- internal/db/migrations-tern/005_add_email_column.sql
- internal/v1/handler.go
- internal/v1/handler_post_compose_test.go
- internal/v1/handler_test.go
This adds an email column to the `composes` table.
> internal: Record email addresses

- templates/image-builder.yml
Also dump the email addresses with floorist, which got enabled through #821
Fixes HMS-2051
> HMS-2051 templates: Include email in FloorPlan

- templates/iqe-trigger-integration.yml
> templates/testing: fix selenium java options parameter

- test/cases/api.sh
Changing ACCOUNT_ORG variables from base64 to plain JSON to improve readability.
> tests: improvements for rhn/cdn credentials

- .golangci.yml
- cmd/image-builder-db-test/main_test.go
- cmd/image-builder/main.go
- internal/db/db.go
- internal/db/db_blueprints.go
- internal/db/migrations-tern/006_create_table_blueprints.sql
- internal/tutils/psql.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
This is my proposal for the create blueprint endpoint. It is 1:1 copy of the payload from the create compose request. Let’s discuss the API first, then I will start working on the code and DDL.
> api: create and delete blueprint endpoint

- go.mod
- go.sum
- internal/logger/logger.go
- internal/logger/logger_test.go
- vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
- vendor/github.com/hashicorp/go-retryablehttp/CODEOWNERS
- vendor/github.com/hashicorp/go-retryablehttp/LICENSE
- vendor/github.com/hashicorp/go-retryablehttp/client.go
- vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
- vendor/github.com/osbuild/osbuild-composer/pkg/splunk_logger/LICENSE
- vendor/github.com/osbuild/osbuild-composer/pkg/splunk_logger/splunk_hook.go
- vendor/github.com/osbuild/osbuild-composer/pkg/splunk_logger/splunk_logger.go
- vendor/github.com/sirupsen/logrus/README.md
- vendor/github.com/sirupsen/logrus/writer.go
- vendor/github.com/stretchr/testify/assert/assertion_compare.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertion_order.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/assert/doc.go
- vendor/github.com/stretchr/testify/assert/http_assertions.go
- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/modules.txt
and delete duplicate code
cleanup after COMPOSER-2051
> internal/logger: use splunk_logger pkg

- HACKING.md
> docs: fix link in HACKING.md

- .gitignore
- HACKING.md
- go.mod
- go.sum
- internal/config/utils.go
- vendor/github.com/joho/godotenv/.gitignore
- vendor/github.com/joho/godotenv/LICENCE
- vendor/github.com/joho/godotenv/README.md
- vendor/github.com/joho/godotenv/godotenv.go
- vendor/github.com/joho/godotenv/parser.go
- vendor/modules.txt
For local developement, enable having local.env file with config variables.
This is just for ease of local developement.
> config: enable loading dotenv file

- cmd/image-builder-db-test/main_test.go
Adding test for https://github.com/osbuild/image-builder/pull/921
> test: Add DB test for inserting Blueprint compose

- .github/workflows/codeql.yml
- .github/workflows/gosec.yml
- .github/workflows/tests.yml
This will enable a merge queue!
> .github/workflows: run workflows on merge_group events

- cmd/image-builder/main.go
To help debug lack of issues showing up on glitchtip
https://issues.redhat.com/browse/HMS-1986
> image-builder: log a warning msg when glitchtip not initialized

- templates/image-builder.yml
to hide difference between stage & prod secret names
> templates: parameterize glitchtip/sentry secret name

- cmd/image-builder/main.go
- vendor/github.com/getsentry/sentry-go/logrus/logrusentry.go
- vendor/modules.txt
Add a logrus hook to send Error logs to sentry as well
https://issues.redhat.com/browse/HMS-1986
> image-builder: improve sentry integration

- test/cases/api.sh
Disable custom repositories tests.
> test: disable repository tests

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
- test/cases/api.sh
This PR reverts the previous commits that disabled the custom repositories feature in image-builder.
> Re-enable custom repositories (HMS-3480)

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler.go
- internal/v1/handler_blueprints.go
Creates OpenAPI components for Meta and Links to standartize List responses.
Refs HMS-3308
> v1/api: Add proper OpenAPI components for Meta and Links

- internal/v1/handler_post_compose_test.go
When non existing distribution compose is requested image builder should intercept the query and return the error to user.
> Test: Add test for non existing distribution compose

- cmd/image-builder/logging.go
- cmd/image-builder/main.go
- internal/config/utils.go
- internal/db/db_trace.go
- internal/db/db_trace_test.go
- internal/v1/server.go
This pull request improves the readability of SQL logs by formatting them in a more readable way. It also adds unit tests to ensure the correctness of the formatting function.
> Improve SQL logging readability

- cmd/image-builder-db-test/main_test.go
- internal/common/quota.go
- internal/db/db.go
- internal/v1/handler.go
- internal/v1/handler_compose_image.go
- internal/v1/handler_test.go
this commit add context to all ledt function at db.go file
> add logger to all functions that doesn't contain context

- internal/composer/openapi.v2.gen.go
- internal/composer/openapi.v2.yml
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
Update the specs and add the new Installer customizations to the API.
See https://github.com/osbuild/osbuild-composer/pull/4005 and further links.
> Add Installer customizations to API

- cmd/image-builder-db-test/main_test.go
- go.mod
- go.sum
- internal/db/migrations-tern/011_add_blueprints_unique_name_constraint.sql
- internal/tutils/tutils.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
- vendor/github.com/jackc/pgerrcode/LICENSE
- vendor/github.com/jackc/pgerrcode/README.md
- vendor/github.com/jackc/pgerrcode/errcode.go
- vendor/github.com/jackc/pgerrcode/gen.rb
- vendor/modules.txt
Validates name to regexp and adds uniqueness constraint for Blueprint.
Refs HMS-3801
> v1/api: Validate Blueprint name (HMS-3801)

- pr_check.sh
This enabled features flags to be checked in ephemeral.
> pr_check: Deploy unleash-proxy to enable feature flags

- .github/workflows/openscap.yml
Add a workflow dispatcher for generating OpenSCAP configs. Also, create a schedule for the configs
to be checked once a week. If there are any changes create a pull request for this.
> workflows: automate OpenSCAP config generation.

- internal/v1/handler_recommend_package.go
- internal/v1/handler_recommend_package_test.go
Unmarshal the response into an appropriate struct.
>  v1: fix the response data from the recommendation service

- .github/workflows/openscap.yml
Fix the automation since it was failing as some dependencies weren’t installed.
> workflows: fix openscap deps

- internal/v1/api.yaml
this commit remove recommendationsResponse item from schema
> v1: remove recommendationsResponse item from schema

- templates/image-builder.yml
Adding two customizations we will want to track in the metrics reports - a quick sanity check would be great!
> floorist: Add openscap and snapshot customizations

- templates/image-builder.yml
Done in collaboration with @avitova and tested on few local data, so it should work :thinking:
> floorplan: add blueprint version and id

- templates/image-builder.yml
UUID's are not compatible with data frames. This should help.
> floorplan: cast uuid type to string

- distributions/centos-9/centos-9.json
- distributions/rhel-94/rhel-94.json
> distributions/el9: build wsl (HMS-4207)

- pr_check.sh
- templates/iqe-trigger-integration.yml
It actually makes more sense than production for pr_check.
> pr_check: Change ref-env to insights-stage

- templates/iqe-trigger-integration.yml
Name update from hms-integration to insights-experiences.
> ci(HMS-3962): Update Integration test image for IQE

- cmd/image-builder/main.go
- internal/clients/recommendations/client.go
- internal/oauth2/dummy_token.go
- internal/oauth2/lazy_token.go
- internal/oauth2/lazy_token_test.go
- internal/v1/handler_recommend_package_test.go
- internal/v1/server_test.go
this commit refactor token in this project:
1) Create a new file lazy_token.go
2) create NextToken(context.Context) string function that will check if token exists already and is not expiring in 1 minute or not expired. in other case it will require a new token, stores expiration time as well as the token itself and return it
4) Create a dummy implementation of Tokener that will return just a string "testtoken"
5) Create an interface named Tokener with the Token(ctx) method
> refactor token in image builder (HMS-3921)

- cmd/image-builder/logging.go
- cmd/image-builder/logging_test.go
also adding the missing tests
Fixes #1248
> image-builder/logging: fix crash for missing fields

- cmd/image-builder/main.go
- internal/clients/recommendations/client.go
- internal/config/config.go
- internal/v1/server_test.go
- templates/image-builder.yml
this commit add RECOMMENDATIONS_PROXY to image builder configuration to support the vpn problem
> internal: add RECOMMENDATIONS_PROXY to the configuration

- cmd/image-builder/main.go
- internal/clients/composer/client.go
- internal/config/config.go
- internal/oauth2/dummy_token.go
- internal/v1/server_test.go
this commit refactor token of composer client, and using the lazy token
> refactor token of composer client <HMS-4369>

- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
This is a followup related to [this thread](https://github.com/osbuild/image-builder/pull/1264#discussion_r1684287363).
Let me know if that's what you had in mind.
> v1/api: Change empty structs to nil for blueprint export

- cmd/image-builder-db-test/main_test.go
- internal/db/db.go
- internal/db/db_blueprints.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
Allow fetch specific Blueprint version, to allow versioning diff in the UI.
> api/v1: Allow fetching specific blueprint version (HMS-4512)

- internal/v1/handler.go
this commit refactor 'GetComposes' method to improve error handling and formatting.
- Enhanced error messages for better debugging and added detailed logging.
- Modified the response formatting for better readability and performance.
- Updated `GetComposes` method to use `make` for preallocating the response slice.
> v1/internal: refactor GetComposes handler

- internal/v1/handler.go
this commit imporve GetDisributions method by
- Add `filterDistributions` function to handle the filtering of restricted distributions.
- Enhance error messages to provide more context for debugging.
- Update error handling in `GetDistributions` to ensure proper HTTP status code is returned.
> internal/v1: Improve error handling in `GetDistributions` method

- Makefile
mini followup of #1299 
Thanks @mvo5 for the hint
> Makefile: remove obsolete comment

- codecov.yml
… to make codecov more visible
> codecov.yml: add comments to the PR

- cmd/image-builder/main.go
This should improve the usability of `gitRev()` to be more generic.
Although this returns a string in case of errors but that's on purpose (see code-comment)
followup of #1323 
---
@mvo5 please check
also please check if I should create a new error class or just wrap and unwrap the string like I did as it's not really important here.
> cmd/image-builder/main: restructure gitRev for reusability

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
Instead of returning a 500, return a 400 with some a reason.
> v1: 400 when requesting snapshots on repos that don't have them (HMS-4481)

- README.md
> readme: add discussions link

- internal/v1/handler_blueprints_test.go
While reviewing PR#1350 I noticed that there is some repetition that could be extracted into a common helper. This commit does this and adds a new `makeTestServer()` that creates the DB, starts the db and token servers and passes a cleanup/shutdown helper back.
> handlers: extract `makeTestServer()` test helper

- .golangci.yml
> linter: exclude vendor/ directory

- .github/workflows/pr_best_practices.yml
This change allows for using the command to create Jira Tasks under a given Epic both in a pull request comment or in the pull request description.
> github/actions: Add pr best practices check (HMS-5161)

- internal/clients/composer/openapi.v2.gen.go
- internal/clients/composer/openapi.v2.yml
Changing the api manually, related to https://github.com/osbuild/osbuild-composer/pull/4487/
> internal: update compose api specs

- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
This was an oversight when adding all the customizations.
> v1: support hostname customization

- .github/workflows/tests.yml
- cmd/image-builder-db-test/main_test.go
- cmd/image-builder-maintenance/config.go
- cmd/image-builder-maintenance/db.go
- internal/clients/compliance/client.go
- internal/clients/content_sources/client.go
- internal/clients/provisioning/client.go
- internal/common/allow.go
- internal/common/quota.go
- internal/db/db.go
- internal/db/db_blueprints.go
- internal/distribution/distribution.go
- internal/distribution/distribution_test.go
- internal/distribution/distroregistry.go
- internal/distribution/distroregistry_test.go
- internal/tutils/psql.go
- internal/unleash/unleash.go
- internal/v1/handler.go
- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
- internal/v1/handler_compose_image.go
- internal/v1/handler_get_compose_status_test.go
- internal/v1/handler_post_compose_test.go
- internal/v1/handler_recommend_package_test.go
- internal/v1/handler_test.go
- internal/v1/mocks/content_sources.go
- internal/v1/oscap.go
- internal/v1/server.go
> fix: fix linter errors

- go.mod
- go.sum
> build(deps): update images to v0.129.0

- internal/tutils/tutils.go
All of these functions do pretty much the same thing other than the http method changing.
> tutils: remove duplication

- internal/clients/composer/client.go
- internal/clients/recommendations/client.go
Noticed one unwrapped doer call and two missed error checks. This fixes it.
> fix: missed nil checks for doer

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler.go
- internal/v1/handler_blueprints.go
- internal/v1/handler_oscap.go
- internal/v1/handler_test.go
JIRA: [HMS-5939](https://issues.redhat.com/browse/HMS-5939)
> Policy get customizations (HMS-5939)

- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_blueprints.go
Makes it easier to filter for it in the frontend.
> v1: add operation id to fixup blueprint endpoint

- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
This helps to prevent users from sharing tokens and certificates.
My question is...should we try to redact this for get as well? It might make sense, but just the idea of having to regenerate the satellite command and upload certificates every time you edit the blueprint sounds a bit annoying?
I have the rest of the frontend-side work ready, so I thought that I could prepare the backend-side while we are waiting for iqe modifications.
> v1: redact satellite token and certs (HMS-4590)

- internal/v1/handler_blueprints.go
- internal/v1/handler_blueprints_test.go
Similar to #1515, passwords need to be forwarded to composer in order for them to take effect.
> v1: don't redact passwords when starting a compose from blueprint (HMS-6047)

- templates/image-builder.yml
This adds hostname, kernel and firewall to query so we're able to track them in the metrics report.
> floorist: Add new customization options to query

- internal/v1/handler.go
- internal/v1/handler_test.go
> v1: redact passwords when querying list of composes

- distributions/fedora-42/fedora-42.json
- internal/distribution/distroregistry_test.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_test.go
> distributions: add fedora-42

- internal/tmpl/aap-first-boot-script.tmpl.txt
- internal/tmpl/aap-first-boot.tmpl.service
- internal/tmpl/params.go
- internal/tmpl/render.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
Add customization options for the Ansible Automation Platform which then converts the options into a first boot script.
> ansible automation platform first boot registration (HMS-4840)

- distributions/rhel-10.0/rhel-10.0.json
> distributions: add vsphere and vsphere-ova to rhel-10 (HMS-8651)

- distributions/centos-10/centos-10.json
- distributions/centos-9/centos-9.json
- distributions/rhel-10-beta/rhel-10-beta.json
- distributions/rhel-10-nightly/rhel-10-nightly.json
- distributions/rhel-10.0-nightly/rhel-10.0-nightly.json
- distributions/rhel-10.0/rhel-10.0.json
- distributions/rhel-10.1-nightly/rhel-10.1-nightly.json
- distributions/rhel-9-beta/rhel-9-beta.json
- distributions/rhel-9-nightly/rhel-9-nightly.json
- distributions/rhel-9.6-nightly/rhel-9.6-nightly.json
- distributions/rhel-9.6/rhel-9.6.json
- distributions/rhel-9.7-nightly/rhel-9.7-nightly.json
- distributions/rhel-90/rhel-90.json
- distributions/rhel-91/rhel-91.json
- distributions/rhel-92/rhel-92.json
- distributions/rhel-93/rhel-93.json
- distributions/rhel-94/rhel-94.json
- distributions/rhel-95/rhel-95.json
- internal/distribution/distribution_test.go
- internal/distribution/distroregistry_test.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_test.go
> add openshift-virt image type to EL9 and EL10

- internal/tmpl/aap-first-boot-script.tmpl.txt
- internal/tmpl/params.go
- internal/v1/api.go
- internal/v1/api.yaml
- internal/v1/handler_compose_image.go
- internal/v1/handler_post_compose_test.go
The AAP registration needs slightly different input values than were expected at first.
First time diving into the CRC project and writing Go, so fingers crossed it all makes sense. No promises it’s perfect—there might be some rookie mistakes lurking :smile:
> aap: edit inputs for provisioning call
